//# Kompletní databáze 300 cvičení pro Czech by Lukas
//# cases: 2-genitiv, 3-dativ, 4-akuzativ, 5-vokativ, 6-lokál, 7-instrumentál

practice_database = [
    //# --- ZÁKLADNÍ VZORY (A0 Essentials) ---
    {"en": "person", "lemma": "člověk", "gender": "masc_anim (pán)", "case": 2, "sentence": "Potkal jsem jednoho __________.", "answer": "člověka"},
    {"en": "sir / Mr.", "lemma": "pán", "gender": "masc_anim (pán)", "case": 3, "sentence": "Pomůžu tamtomu __________.", "answer": "pánovi"},
    {"en": "man", "lemma": "muž", "gender": "masc_anim (muž)", "case": 4, "sentence": "Vidím tamtoho __________.", "answer": "muže"},
    {"en": "woman", "lemma": "žena", "gender": "fem (žena)", "case": 7, "sentence": "Jdu tam se svou __________.", "answer": "ženou"},
    {"en": "rose", "lemma": "růže", "gender": "fem (růže)", "case": 2, "sentence": "Váza je bez __________.", "answer": "růže"},
    {"en": "city", "lemma": "město", "gender": "neutr (město)", "case": 6, "sentence": "Bydlím v tomto __________.", "answer": "městě"},
    {"en": "sea", "lemma": "moře", "gender": "neutr (moře)", "case": 4, "sentence": "Chci vidět __________.", "answer": "moře"},
    {"en": "house", "lemma": "dům", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Jdu do __________.", "answer": "domu"},
    {"en": "castle", "lemma": "hrad", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Byli jsme na __________.", "answer": "hradě"},
    {"en": "machine", "lemma": "stroj", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Pracuji s tímto __________.", "answer": "strojem"},
    {"en": "chairman", "lemma": "předseda", "gender": "masc_anim (předseda)", "case": 3, "sentence": "Píšu panu __________.", "answer": "předsedovi"},
    {"en": "judge", "lemma": "soudce", "gender": "masc_anim (soudce)", "case": 4, "sentence": "Hledáme __________.", "answer": "soudce"},
    {"en": "song", "lemma": "píseň", "gender": "fem (píseň)", "case": 4, "sentence": "Zpívám tu __________.", "answer": "píseň"},
    {"en": "bone", "lemma": "kost", "gender": "fem (kost)", "case": 2, "sentence": "Pes je bez __________.", "answer": "kosti"},
    {"en": "chicken", "lemma": "kuře", "gender": "neutr (kuře)", "case": 4, "sentence": "Jím pečené __________.", "answer": "kuře"},
    {"en": "building", "lemma": "stavení", "gender": "neutr (stavení)", "case": 6, "sentence": "Bydlí v tom starém __________.", "answer": "stavení"},
    {"en": "year", "lemma": "rok", "gender": "masc_inan (hrad)", "case": 6, "sentence": "V tomto __________ se vše změní.", "answer": "roce"},
    {"en": "hand", "lemma": "ruka", "gender": "fem (žena)", "case": 7, "sentence": "Mávám __________.", "answer": "rukou"},
    {"en": "child", "lemma": "dítě", "gender": "neutr (kuře)", "case": 3, "sentence": "Dám to tomu __________.", "answer": "dítěti"},
    {"en": "way", "lemma": "cesta", "gender": "fem (žena)", "case": 4, "sentence": "Ukážete mi __________?", "answer": "cestu"},

    //# --- JÍDLO A PITÍ ---
    {"en": "beer", "lemma": "pivo", "gender": "neutr (město)", "case": 4, "sentence": "Piju studené __________.", "answer": "pivo"},
    {"en": "water", "lemma": "voda", "gender": "fem (žena)", "case": 2, "sentence": "Chci sklenici __________.", "answer": "vody"},
    {"en": "rice", "lemma": "rýže", "gender": "fem (růže)", "case": 4, "sentence": "Máš rád __________?", "answer": "rýži"},
    {"en": "salmon", "lemma": "losos", "gender": "masc_anim (pán)", "case": 4, "sentence": "Dám si čerstvého __________.", "answer": "lososa"},
    {"en": "eel", "lemma": "úhoř", "gender": "masc_anim (muž)", "case": 2, "sentence": "Mám strach z __________.", "answer": "úhoře"},
    {"en": "sugar", "lemma": "cukr", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Potřebuju __________.", "answer": "cukr"},
    {"en": "tea", "lemma": "čaj", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Snídám se sladkým __________.", "answer": "čajem"},
    {"en": "coffee", "lemma": "káva", "gender": "fem (žena)", "case": 4, "sentence": "Piju horkou __________.", "answer": "kávu"},
    {"en": "dessert", "lemma": "moučník", "gender": "masc_inan (hrad)", "case": 3, "sentence": "Ke __________ si dám kávu.", "answer": "moučníku"},
    {"en": "dinner", "lemma": "večeře", "gender": "fem (růže)", "case": 4, "sentence": "Vařím __________.", "answer": "večeři"},
    {"en": "drink", "lemma": "nápoj", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hledám osvěžující __________.", "answer": "nápoj"},
    {"en": "dumpling", "lemma": "knedlík", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Dám si to s __________.", "answer": "knedlíkem"},
    {"en": "fish", "lemma": "ryba", "gender": "fem (žena)", "case": 4, "sentence": "Mám rád pečenou __________.", "answer": "rybu"},
    {"en": "French fries", "lemma": "hranolky", "gender": "masc_inan (hrad - pl)", "case": 7, "sentence": "Chci řízek s __________.", "answer": "hranolky"},
    {"en": "fruit", "lemma": "ovoce", "gender": "neutr (růže/moře)", "case": 2, "sentence": "Jím hodně __________.", "answer": "ovoce"},
    {"en": "ice-cream", "lemma": "zmrzlina", "gender": "fem (žena)", "case": 4, "sentence": "Děti milují __________.", "answer": "zmrzlinu"},
    {"en": "lunch", "lemma": "oběd", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Bude to až po __________.", "answer": "obědě"},
    {"en": "napkin", "lemma": "ubrousek", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Utřu se __________.", "answer": "ubrouskem"},
    {"en": "pasta", "lemma": "těstoviny", "gender": "fem (žena - pl)", "case": 4, "sentence": "Dnes vařím __________.", "answer": "těstoviny"},
    {"en": "potatoes", "lemma": "brambory", "gender": "masc_inan (hrad - pl)", "case": 2, "sentence": "Kilogram __________.", "answer": "brambor"},
    {"en": "restaurant", "lemma": "restaurace", "gender": "fem (růže)", "case": 6, "sentence": "Jsme v __________.", "answer": "restauraci"},
    {"en": "salad", "lemma": "salát", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Udělám dobrý __________.", "answer": "salát"},
    {"en": "sauce", "lemma": "omáčka", "gender": "fem (žena)", "case": 4, "sentence": "Mám rád koprovou __________.", "answer": "omáčku"},
    {"en": "sauerkraut", "lemma": "kyselé zelí", "gender": "neutr (stavení)", "case": 4, "sentence": "Chci kachnu a __________.", "answer": "kyselé zelí"},
    {"en": "side dish", "lemma": "příloha", "gender": "fem (žena)", "case": 4, "sentence": "Zvolte si __________.", "answer": "přílohu"},
    {"en": "soup", "lemma": "polévka", "gender": "fem (žena)", "case": 4, "sentence": "Jím horkou __________.", "answer": "polévku"},
    {"en": "tip", "lemma": "spropitné", "gender": "neutr (adj/stavení)", "case": 4, "sentence": "Nechal jsem velké __________.", "answer": "spropitné"},
    {"en": "vegetables", "lemma": "zelenina", "gender": "fem (žena)", "case": 2, "sentence": "Talíř plný __________.", "answer": "zeleniny"},
    {"en": "wine", "lemma": "víno", "gender": "neutr (město)", "case": 2, "sentence": "Sklenička __________.", "answer": "vína"},
    {"en": "waitress", "lemma": "servírka", "gender": "fem (žena)", "case": 3, "sentence": "Zaplatím __________.", "answer": "servírce"},
    {"en": "waiter", "lemma": "číšník", "gender": "masc_anim (pán)", "case": 4, "sentence": "Zavolám __________.", "answer": "číšníka"},
    {"en": "chef", "lemma": "kuchař", "gender": "masc_anim (muž)", "case": 6, "sentence": "Mluvím o tom __________.", "answer": "kuchaři"},
    {"en": "cafe", "lemma": "kavárna", "gender": "fem (žena)", "case": 6, "sentence": "Sejdeme se v __________.", "answer": "kavárně"},
    {"en": "order", "lemma": "objednávka", "gender": "fem (žena)", "case": 2, "sentence": "Číslo vaší __________.", "answer": "objednávky"},

    //# --- POMŮCKY A PŘEDMĚTY ---
    {"en": "pencil", "lemma": "tužka", "gender": "fem (žena)", "case": 7, "sentence": "Píšu __________.", "answer": "tužkou"},
    {"en": "soap", "lemma": "mýdlo", "gender": "neutr (město)", "case": 7, "sentence": "Myju se __________.", "answer": "mýdlem"},
    {"en": "spoon", "lemma": "lžička", "gender": "fem (žena)", "case": 7, "sentence": "Jím to malou __________.", "answer": "lžičkou"},
    {"en": "car", "lemma": "auto", "gender": "neutr (město)", "case": 7, "sentence": "Jedu novým __________.", "answer": "autem"},
    {"en": "yacht", "lemma": "jachta", "gender": "fem (žena)", "case": 6, "sentence": "Byl jsem na __________.", "answer": "jachtě"},
    {"en": "device", "lemma": "přístroj", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Měřím to tímto __________.", "answer": "přístrojem"},
    {"en": "gift", "lemma": "dárek", "gender": "masc_inan (hrad)", "case": 3, "sentence": "Děkuji za radost z __________.", "answer": "dárku"},
    {"en": "computer", "lemma": "počítač", "gender": "masc_inan (stroj)", "case": 3, "sentence": "Rozumím tomu __________.", "answer": "počítači"},
    {"en": "mirror", "lemma": "zrcadlo", "gender": "neutr (město)", "case": 6, "sentence": "Vidím se v __________.", "answer": "zrcadle"},
    {"en": "toy", "lemma": "hračka", "gender": "fem (žena)", "case": 4, "sentence": "Koupím dětem __________.", "answer": "hračku"},
    {"en": "egg", "lemma": "vejce", "gender": "neutr (moře)", "case": 4, "sentence": "Sním jedno __________.", "answer": "vejce"},
    {"en": "stamp", "lemma": "známka", "gender": "fem (žena)", "case": 4, "sentence": "Koupím poštovní __________.", "answer": "známku"},
    {"en": "letter", "lemma": "dopis", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Píšu __________.", "answer": "dopis"},
    {"en": "postcard", "lemma": "pohled", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Posílám __________.", "answer": "pohled"},
    {"en": "package", "lemma": "balík", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Nesu těžký __________.", "answer": "balík"},
    {"en": "money", "lemma": "peníze", "gender": "masc_inan (stroj - pl)", "case": 4, "sentence": "Nemám __________.", "answer": "peníze"},
    {"en": "receipt", "lemma": "účtenka", "gender": "fem (žena)", "case": 4, "sentence": "Ztratil jsem __________.", "answer": "účtenku"},
    {"en": "shampoo", "lemma": "šampon", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Myju si vlasy __________.", "answer": "šamponem"},
    {"en": "towel", "lemma": "ručník", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Utřu se __________.", "answer": "ručníkem"},
    {"en": "creme", "lemma": "krém", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Používám opalovací __________.", "answer": "krém"},
    {"en": "comb", "lemma": "hřeben", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Češu se __________.", "answer": "hřebenem"},
    {"en": "hairdryer", "lemma": "fén", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Suším si vlasy __________.", "answer": "fénem"},
    {"en": "brush", "lemma": "kartáč", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Čistím to __________.", "answer": "kartáčem"},
    {"en": "handkerchief", "lemma": "kapesník", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Máte __________?", "answer": "kapesník"},
    {"en": "an iron", "lemma": "žehlička", "gender": "fem (žena)", "case": 7, "sentence": "Pracuji s horkou __________.", "answer": "žehličkou"},
    {"en": "vacuum cleaner", "lemma": "vysavač", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Uklízím __________.", "answer": "vysavačem"},

    //# --- RODINA A LIDÉ ---
    {"en": "friend (male)", "lemma": "kamarád", "gender": "masc_anim (pán)", "case": 7, "sentence": "Jdu tam s __________.", "answer": "kamarádem"},
    {"en": "boyfriend", "lemma": "přítel", "gender": "masc_anim (muž)", "case": 7, "sentence": "Mluvím se svým __________.", "answer": "přítelem"},
    {"en": "neighbor (m)", "lemma": "soused", "gender": "masc_anim (pán)", "case": 6, "sentence": "Mluvím o svém __________.", "answer": "sousedovi"},
    {"en": "owner (m)", "lemma": "majitel", "gender": "masc_anim (muž)", "case": 6, "sentence": "Zavolám o tom __________.", "answer": "majiteli"},
    {"en": "name", "lemma": "jméno", "gender": "neutr (město)", "case": 4, "sentence": "Napište své __________.", "answer": "jméno"},
    {"en": "surname", "lemma": "příjmení", "gender": "neutr (stavení)", "case": 2, "sentence": "Bez __________ to nejde.", "answer": "příjmení"},
    {"en": "Ms", "lemma": "slečna", "gender": "fem (žena)", "case": 5, "sentence": "Dobré ráno, __________!", "answer": "slečno"},
    {"en": "Mr.", "lemma": "pan", "gender": "masc_anim (pán)", "case": 3, "sentence": "Dám to tomu __________.", "answer": "panovi"},
    {"en": "Mrs.", "lemma": "paní", "gender": "fem (píseň)", "case": 4, "sentence": "Hledám tuhle __________.", "answer": "paní"},
    {"en": "state", "lemma": "stát", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Žiju v tomto __________.", "answer": "státě"},
    {"en": "at sign", "lemma": "zavináč", "gender": "masc_anim (muž)", "case": 4, "sentence": "Napište tam __________.", "answer": "zavináč"},
    {"en": "age", "lemma": "věk", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Uveďte svůj __________.", "answer": "věk"},
    {"en": "gender", "lemma": "pohlaví", "gender": "neutr (stavení)", "case": 4, "sentence": "Vyberte __________.", "answer": "pohlaví"},
    {"en": "husband", "lemma": "manžel", "gender": "masc_anim (pán)", "case": 2, "sentence": "To je auto mého __________.", "answer": "manžela"},
    {"en": "wife", "lemma": "manželka", "gender": "fem (žena)", "case": 4, "sentence": "Mám rád svou __________.", "answer": "manželku"},
    {"en": "partner (m)", "lemma": "partner", "gender": "masc_anim (pán)", "case": 7, "sentence": "Jdu tam se svým __________.", "answer": "partnerem"},
    {"en": "partner (f)", "lemma": "partnerka", "gender": "fem (žena)", "case": 2, "sentence": "Auto mé __________.", "answer": "partnerky"},
    {"en": "wedding", "lemma": "svatba", "gender": "fem (žena)", "case": 6, "sentence": "Byl jsem na __________.", "answer": "svatbě"},
    {"en": "marriage", "lemma": "sňatek", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Den __________.", "answer": "sňatku"},
    {"en": "nationality", "lemma": "národnost", "gender": "fem (kost)", "case": 4, "sentence": "Máte českou __________?", "answer": "národnost"},
    {"en": "citizenship", "lemma": "občanství", "gender": "neutr (stavení)", "case": 4, "sentence": "Chci získat __________.", "answer": "občanství"},
    {"en": "religion", "lemma": "náboženství", "gender": "neutr (stavení)", "case": 2, "sentence": "Svoboda __________.", "answer": "náboženství"},
    {"en": "Christian", "lemma": "křesťan", "gender": "masc_anim (pán)", "case": 4, "sentence": "Znám jednoho __________.", "answer": "křesťana"},
    {"en": "Muslim", "lemma": "muslim", "gender": "masc_anim (pán)", "case": 3, "sentence": "Pomůžu __________.", "answer": "muslimovi"},
    {"en": "Muslim (f)", "lemma": "muslimka", "gender": "fem (žena)", "case": 6, "sentence": "Mluvím o té __________.", "answer": "muslimce"},
    {"en": "atheist", "lemma": "ateista", "gender": "masc_anim (předseda)", "case": 4, "sentence": "Vidím __________.", "answer": "ateistu"},
    {"en": "church", "lemma": "kostel", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Jsme v __________.", "answer": "kostele"},
    {"en": "mosque", "lemma": "mešita", "gender": "fem (žena)", "case": 6, "sentence": "Modlí se v __________.", "answer": "mešitě"},
    {"en": "temple", "lemma": "chrám", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Navštívíme __________.", "answer": "chrám"},
    {"en": "passport", "lemma": "pas", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám u sebe __________.", "answer": "pas"},
    {"en": "visa", "lemma": "vízum", "gender": "neutr (město)", "case": 2, "sentence": "Jsem tu bez __________.", "answer": "víza"},
    {"en": "signature", "lemma": "podpis", "gender": "masc_inan (hrad)", "case": 7, "sentence": "S tvým __________ souhlasím.", "answer": "podpisem"},
    {"en": "family", "lemma": "rodina", "gender": "fem (žena)", "case": 7, "sentence": "Jdu tam s celou __________.", "answer": "rodinou"},
    {"en": "parent", "lemma": "rodič", "gender": "masc_anim (muž)", "case": 3, "sentence": "Pomáhám starému __________.", "answer": "rodiči"},
    {"en": "mother", "lemma": "matka", "gender": "fem (žena)", "case": 4, "sentence": "Hledám svou __________.", "answer": "matku"},
    {"en": "mommy", "lemma": "maminka", "gender": "fem (žena)", "case": 3, "sentence": "Píšu __________.", "answer": "mamince"},
    {"en": "father", "lemma": "otec", "gender": "masc_anim (muž)", "case": 2, "sentence": "Dům mého __________.", "answer": "otce"},
    {"en": "dad", "lemma": "tatínek", "gender": "masc_anim (pán)", "case": 7, "sentence": "Pracuji s __________.", "answer": "tatínkem"},
    {"en": "father (col.)", "lemma": "táta", "gender": "masc_anim (předseda)", "case": 5, "sentence": "Ahoj, __________!", "answer": "táto"},
    {"en": "children", "lemma": "děti", "gender": "fem (kost - pl)", "case": 4, "sentence": "Vidím __________.", "answer": "děti"},
    {"en": "son", "lemma": "syn", "gender": "masc_anim (pán)", "case": 3, "sentence": "Dám to __________.", "answer": "synovi"},
    {"en": "daughter", "lemma": "dcera", "gender": "fem (žena)", "case": 6, "sentence": "Mluvím o své __________.", "answer": "dceři"},
    {"en": "brother", "lemma": "bratrn", "gender": "masc_anim (pán)", "case": 7, "sentence": "Mluvím s __________.", "answer": "bratrem"},
    {"en": "sister", "lemma": "sestra", "gender": "fem (žena)", "case": 2, "sentence": "Auto mé __________.", "answer": "sestry"},
    {"en": "male cousin", "lemma": "bratranec", "gender": "masc_anim (muž)", "case": 4, "sentence": "Potkal jsem __________.", "answer": "bratrance"},
    {"en": "female cousin", "lemma": "sestřenice", "gender": "fem (růže)", "case": 6, "sentence": "Jsme u __________.", "answer": "sestřenice"},
    {"en": "grandma", "lemma": "babička", "gender": "fem (žena)", "case": 3, "sentence": "Dám květinu __________.", "answer": "babičce"},
    {"en": "grandpa", "lemma": "dědeček", "gender": "masc_anim (pán)", "case": 4, "sentence": "Vidím __________.", "answer": "dědečka"},
    {"en": "uncle", "lemma": "strýc", "gender": "masc_anim (muž)", "case": 7, "sentence": "Hraju šachy se __________.", "answer": "strýcem"},
    {"en": "aunt", "lemma": "teta", "gender": "fem (žena)", "case": 4, "sentence": "Hledám __________.", "answer": "tetu"},
    {"en": "glasses", "lemma": "brýle", "gender": "fem (růže - pl)", "case": 4, "sentence": "Nosím __________.", "answer": "brýle"},
    {"en": "eye", "lemma": "oko", "gender": "neutr (město)", "case": 6, "sentence": "Mám něco v __________.", "answer": "oku"},
    {"en": "hair", "lemma": "vlas", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Máš dlouhý __________.", "answer": "vlas"},

    //# --- NAKUPOVÁNÍ A OBCHODY ---
    {"en": "shop", "lemma": "obchod", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Jsme v __________.", "answer": "obchodě"},
    {"en": "supermarket", "lemma": "supermarket", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hledám __________.", "answer": "supermarket"},
    {"en": "bakery", "lemma": "pekařství", "gender": "neutr (stavení)", "case": 6, "sentence": "V __________ voní chleba.", "answer": "pekařství"},
    {"en": "sweet shop", "lemma": "cukrárna", "gender": "fem (žena)", "case": 6, "sentence": "Dáme si dort v __________.", "answer": "cukrárně"},
    {"en": "butcher shop", "lemma": "řeznictví", "gender": "neutr (stavení)", "case": 2, "sentence": "Jdu do __________.", "answer": "řeznictví"},
    {"en": "stationary store", "lemma": "papírnictví", "gender": "neutr (stavení)", "case": 6, "sentence": "Koupím sešity v __________.", "answer": "papírnictví"},
    {"en": "pharmacy", "lemma": "lékárna", "gender": "fem (žena)", "case": 4, "sentence": "Hledám nejbližší __________.", "answer": "lékárnu"},
    {"en": "drug store", "lemma": "drogerie", "gender": "fem (růže)", "case": 2, "sentence": "Jdu do __________.", "answer": "drogerie"},
    {"en": "market", "lemma": "trh", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Koupím zeleninu na __________.", "answer": "trhu"},
    {"en": "grocery store", "lemma": "potraviny", "gender": "masc_inan (hrad - pl)", "case": 6, "sentence": "Jsem v __________.", "answer": "potravinách"},
    {"en": "clothing", "lemma": "oblečení", "gender": "neutr (stavení)", "case": 4, "sentence": "Koupím si nové __________.", "answer": "oblečení"},
    {"en": "shoes", "lemma": "boty", "gender": "fem (žena - pl)", "case": 7, "sentence": "Jdu v nových __________.", "answer": "botách"},
    {"en": "dishes", "lemma": "nádobí", "gender": "neutr (stavení)", "case": 4, "sentence": "Umývám __________.", "answer": "nádobí"},
    {"en": "jacket", "lemma": "bunda", "gender": "fem (žena)", "case": 4, "sentence": "Vezmu si __________.", "answer": "bundu"},
    {"en": "shirt", "lemma": "košile", "gender": "fem (růže)", "case": 4, "sentence": "Zkusím si tu __________.", "answer": "košili"},
    {"en": "trousers", "lemma": "kalhoty", "gender": "fem (žena - pl)", "case": 4, "sentence": "Koupím si __________.", "answer": "kalhoty"},
    {"en": "jeans", "lemma": "džíny", "gender": "fem (žena - pl)", "case": 4, "sentence": "Mám nové __________.", "answer": "džíny"},
    {"en": "t-shirt", "lemma": "tričko", "gender": "neutr (město)", "case": 4, "sentence": "Mám rád tohle __________.", "answer": "tričko"},
    {"en": "sweater", "lemma": "svetr", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Jdu v teplém __________.", "answer": "svetrem"},
    {"en": "dress", "lemma": "šaty", "gender": "masc_inan (hrad - pl)", "case": 4, "sentence": "Koupila si nové __________.", "answer": "šaty"},
    {"en": "skirt", "lemma": "sukně", "gender": "fem (růže)", "case": 4, "sentence": "Líbí se mi ta __________.", "answer": "sukně"},
    {"en": "socks", "lemma": "ponožky", "gender": "fem (žena - pl)", "case": 4, "sentence": "Hledám své __________.", "answer": "ponožky"},
    {"en": "cap", "lemma": "čepice", "gender": "fem (růže)", "case": 4, "sentence": "Vezmu si __________.", "answer": "čepici"},
    {"en": "scarf", "lemma": "šátek", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Jdu se __________.", "answer": "šátkem"},
    {"en": "gloves", "lemma": "rukavice", "gender": "fem (růže - pl)", "case": 4, "sentence": "Mám teplé __________.", "answer": "rukavice"},
    {"en": "umbrella", "lemma": "deštník", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Jdu s __________.", "answer": "deštníkem"},
    {"en": "backpack", "lemma": "batoh", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Nesu těžký __________.", "answer": "batoh"},
    {"en": "handbag", "lemma": "kabelka", "gender": "fem (žena)", "case": 4, "sentence": "Mám novou __________.", "answer": "kabelku"},
    {"en": "changing room", "lemma": "kabinka", "gender": "fem (žena)", "case": 6, "sentence": "Zkusím si to v __________.", "answer": "kabince"},
    {"en": "size", "lemma": "velikost", "gender": "fem (kost)", "case": 4, "sentence": "Potřebuju jinou __________.", "answer": "velikost"},
    {"en": "color", "lemma": "barva", "gender": "fem (žena)", "case": 4, "sentence": "Máte jinou __________?", "answer": "barvu"},
    {"en": "prescription", "lemma": "předpis", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Máte lékařský __________?", "answer": "předpis"},
    {"en": "pill", "lemma": "prášek", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Vezmu si __________.", "answer": "prášek"},
    {"en": "cash desk", "lemma": "pokladna", "gender": "fem (žena)", "case": 6, "sentence": "Zaplatím u __________.", "answer": "pokladně"},
    {"en": "card", "lemma": "karta", "gender": "fem (žena)", "case": 7, "sentence": "Platím __________.", "answer": "kartou"},
    {"en": "service", "lemma": "služba", "gender": "fem (žena)", "case": 4, "sentence": "Hledám tuhle __________.", "answer": "službu"},
    {"en": "dry cleaners", "lemma": "čistírna", "gender": "fem (žena)", "case": 2, "sentence": "Jdu do __________.", "answer": "čistírny"},
    {"en": "launderette", "lemma": "prádelna", "gender": "fem (žena)", "case": 6, "sentence": "Vyzvednu prádlo v __________.", "answer": "prádelně"},
    {"en": "hairdresser's", "lemma": "kadeřnictví", "gender": "neutr (stavení)", "case": 4, "sentence": "Hledám levné __________.", "answer": "kadeřnictví"},
    {"en": "rental", "lemma": "půjčovna", "gender": "fem (žena)", "case": 2, "sentence": "Auto je z __________.", "answer": "půjčovny"},
    {"en": "exchange office", "lemma": "směnárna", "gender": "fem (žena)", "case": 6, "sentence": "Vyměním peníze ve __________.", "answer": "směnárně"},
    {"en": "shop assistant (f)", "lemma": "prodavačka", "gender": "fem (žena)", "case": 3, "sentence": "Dám to __________.", "answer": "prodavačce"},
    {"en": "cashier", "lemma": "pokladní", "gender": "masc_anim (adj/muž)", "case": 3, "sentence": "Řeknu to __________.", "answer": "pokladnímu"},
    {"en": "bank", "lemma": "banka", "gender": "fem (žena)", "case": 2, "sentence": "Jdu do __________.", "answer": "banky"},
    {"en": "ATM", "lemma": "bankomat", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hledám nejbližší __________.", "answer": "bankomat"},
    {"en": "bank account", "lemma": "účet", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Mám peníze na __________.", "answer": "účtu"},
    {"en": "currency", "lemma": "měna", "gender": "fem (žena)", "case": 4, "sentence": "Potřebujeme místní __________.", "answer": "měnu"},
    {"en": "exchange rate", "lemma": "kurz", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Sledujeme __________.", "answer": "kurz"},

    //# --- CESTOVÁNÍ ---
    {"en": "fare", "lemma": "jízdné", "gender": "neutr (stavení)", "case": 4, "sentence": "Zaplatím __________.", "answer": "jízdné"},
    {"en": "reservation", "lemma": "rezervace", "gender": "fem (růže)", "case": 4, "sentence": "Mám __________.", "answer": "rezervaci"},
    {"en": "passenger", "lemma": "cestující", "gender": "masc_anim (adj/muž)", "case": 2, "sentence": "Bez __________ je vlak prázdný.", "answer": "cestujícího"},
    {"en": "destination", "lemma": "destinace", "gender": "fem (růže)", "case": 6, "sentence": "Mluvím o naší __________.", "answer": "destinaci"},
    {"en": "itinerary", "lemma": "itinerář", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Naplánuju __________.", "answer": "itinerář"},
    {"en": "holiday", "lemma": "dovolená", "gender": "fem (adj/žena)", "case": 4, "sentence": "Mám skvělou __________.", "answer": "dovolenou"},
    {"en": "vacation", "lemma": "prázdniny", "gender": "fem (žena - pl)", "case": 2, "sentence": "Během __________ cestujeme.", "answer": "prázdnin"},
    {"en": "delay", "lemma": "zpoždění", "gender": "neutr (stavení)", "case": 4, "sentence": "Letadlo má __________.", "answer": "zpoždění"},
    {"en": "luggage", "lemma": "zavazadlo", "gender": "neutr (město)", "case": 2, "sentence": "Jsem bez __________.", "answer": "zavazadla"},

    //# --- DENNÍ REŽIM ---
    {"en": "handkerchief", "lemma": "kapesník", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Utřu se __________.", "answer": "kapesníkem"},
    {"en": "shampoo", "lemma": "šampon", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Koupím __________.", "answer": "šampon"},
    {"en": "iron", "lemma": "žehlička", "gender": "fem (žena)", "case": 4, "sentence": "Zapnu __________.", "answer": "žehličku"},

    //# --- PRÁCE A POVOLÁNÍ ---
    {"en": "employment", "lemma": "zaměstnání", "gender": "neutr (stavení)", "case": 4, "sentence": "Hledám nové __________.", "answer": "zaměstnání"},
    {"en": "occupation", "lemma": "povolání", "gender": "neutr (stavení)", "case": 2, "sentence": "Podle __________ je lékař.", "answer": "povolání"},
    {"en": "labourer (m)", "lemma": "dělník", "gender": "masc_anim (pán)", "case": 7, "sentence": "Mluvím s __________.", "answer": "dělníkem"},
    {"en": "driver (f)", "lemma": "řidička", "gender": "fem (žena)", "case": 4, "sentence": "Zavolám paní __________.", "answer": "řidičku"},
    {"en": "shop assistant (m)", "lemma": "prodavač", "gender": "masc_anim (pán)", "case": 4, "sentence": "Vidím __________.", "answer": "prodavače"},
    {"en": "waiter", "lemma": "číšník", "gender": "masc_anim (pán)", "case": 3, "sentence": "Dám to __________.", "answer": "číšníkovi"},
    {"en": "hairdresser (f)", "lemma": "kadeřnice", "gender": "fem (růže)", "case": 6, "sentence": "Byla jsem u __________.", "answer": "kadeřnice"},
    {"en": "clerk (m)", "lemma": "úředník", "gender": "masc_anim (pán)", "case": 4, "sentence": "Hledám toho __________.", "answer": "úředníka"},
    {"en": "accountant", "lemma": "účetní", "gender": "masc_anim (adj/muž)", "case": 7, "sentence": "Mluvím s panem __________.", "answer": "účetním"},
    {"en": "doctor (m)", "lemma": "lékař", "gender": "masc_anim (muž)", "case": 3, "sentence": "Jdu k __________.", "answer": "lékaři"},
    {"en": "teacher (f)", "lemma": "učitelka", "gender": "fem (žena)", "case": 4, "sentence": "Poslouchám __________.", "answer": "učitelku"},
    {"en": "lawyer (m)", "lemma": "právník", "gender": "masc_anim (pán)", "case": 4, "sentence": "Potřebuju __________.", "answer": "právníka"},
    {"en": "judge (f)", "lemma": "soudkyně", "gender": "fem (růže)", "case": 3, "sentence": "Věřím __________.", "answer": "soudkyni"},
    {"en": "policeman", "lemma": "policista", "gender": "masc_anim (předseda)", "case": 2, "sentence": "Ptal jsem se __________.", "answer": "policisty"},
    {"en": "journalist (m)", "lemma": "novinář", "gender": "masc_anim (muž)", "case": 7, "sentence": "Mluvím s __________.", "answer": "novinářem"},
    {"en": "businessman", "lemma": "podnikatel", "gender": "masc_anim (muž)", "case": 4, "sentence": "Hledám __________.", "answer": "podnikatele"},
    {"en": "student (f)", "lemma": "studentka", "gender": "fem (žena)", "case": 3, "sentence": "Dám to té __________.", "answer": "studentce"},
    {"en": "workplace", "lemma": "pracoviště", "gender": "neutr (moře)", "case": 6, "sentence": "Jsme na __________.", "answer": "pracovišti"},
    {"en": "factory", "lemma": "továrna", "gender": "fem (žena)", "case": 2, "sentence": "Jdu z __________.", "answer": "továrny"},
    {"en": "enterprise", "lemma": "podnik", "gender": "masc_inan (hrad)", "case": 6, "sentence": "V tomto __________ pracuju.", "answer": "podniku"},
    {"en": "construction", "lemma": "stavba", "gender": "fem (žena)", "case": 6, "sentence": "Jsme na __________.", "answer": "stavbě"},
    {"en": "company", "lemma": "firma", "gender": "fem (žena)", "case": 3, "sentence": "Píšu té __________.", "answer": "firmě"},
    {"en": "farm", "lemma": "farma", "gender": "fem (žena)", "case": 6, "sentence": "Děti jsou na __________.", "answer": "farmě"},
    {"en": "employer", "lemma": "zaměstnavatel", "gender": "masc_anim (muž)", "case": 4, "sentence": "Hledám __________.", "answer": "zaměstnavatele"},
    {"en": "employee (m)", "lemma": "zaměstnanec", "gender": "masc_anim (muž)", "case": 2, "sentence": "Bez __________ to nejde.", "answer": "zaměstnance"},
    {"en": "employee (f)", "lemma": "zaměstnankyně", "gender": "fem (růže)", "case": 4, "sentence": "Hledám paní __________.", "answer": "zaměstnankyni"},
    {"en": "director (m)", "lemma": "ředitel", "gender": "masc_anim (muž)", "case": 3, "sentence": "Dám to panu __________.", "answer": "řediteli"},
    {"en": "leader", "lemma": "vedoucí", "gender": "masc_anim (adj/muž)", "case": 4, "sentence": "Zavolám pana __________.", "answer": "vedoucího"},
    {"en": "wage", "lemma": "mzda", "gender": "fem (žena)", "case": 7, "sentence": "Se svou __________ jsem spokojen.", "answer": "mzdou"},
    {"en": "salary", "lemma": "plat", "gender": "masc_inan (hrad)", "case": 6, "sentence": "O svém __________ nemluvím.", "answer": "platu"},
    {"en": "bonus", "lemma": "odměna", "gender": "fem (žena)", "case": 4, "sentence": "Dostal jsem __________.", "answer": "odměnu"},
    {"en": "experience", "lemma": "praxe", "gender": "fem (růže)", "case": 4, "sentence": "Mám dlouhou __________.", "answer": "praxi"},
    {"en": "CV", "lemma": "životopis", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Posílám svůj __________.", "answer": "životopis"},
    {"en": "job centre", "lemma": "úřad práce", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Jdu z __________.", "answer": "úřadu práce"},
    {"en": "office", "lemma": "kancelář", "gender": "fem (píseň)", "case": 6, "sentence": "Jsme v __________.", "answer": "kanceláři"},

    //# --- KONÍČKY ---
    {"en": "holiday (public)", "lemma": "svátek", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Oslavíme __________.", "answer": "svátek"},
    {"en": "walk", "lemma": "procházka", "gender": "fem (žena)", "case": 4, "sentence": "Jdeme na __________.", "answer": "procházku"},
    {"en": "trip", "lemma": "výlet", "gender": "masc_inan (hrad)", "case": 3, "sentence": "Hurá k __________!", "answer": "výletu"},
    {"en": "pub", "lemma": "hospoda", "gender": "fem (žena)", "case": 6, "sentence": "Jsme v __________.", "answer": "hospodě"},
    {"en": "shopping", "lemma": "nakupování", "gender": "neutr (stavení)", "case": 4, "sentence": "Mám rád __________.", "answer": "nakupování"},
    {"en": "visit", "lemma": "návštěva", "gender": "fem (žena)", "case": 4, "sentence": "Máme __________.", "answer": "návštěvu"},
    {"en": "hobby", "lemma": "koníček", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Máš nějaký __________?", "answer": "koníček"},
    {"en": "violin", "lemma": "housle", "gender": "fem (růže - pl)", "case": 4, "sentence": "Hraju na __________.", "answer": "housle"},
    {"en": "chess", "lemma": "šachy", "gender": "masc_inan (hrad - pl)", "case": 4, "sentence": "Hraju __________.", "answer": "šachy"},
    {"en": "cards", "lemma": "karty", "gender": "fem (žena - pl)", "case": 4, "sentence": "Hrajeme __________.", "answer": "karty"},
    {"en": "billiards", "lemma": "kulečník", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hraju __________.", "answer": "kulečník"},
    {"en": "garden", "lemma": "zahrada", "gender": "fem (žena)", "case": 6, "sentence": "Jsme na __________.", "answer": "zahradě"},

    //# --- BYDLENÍ ---
    {"en": "apartment", "lemma": "byt", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Bydlím v __________.", "answer": "bytě"},
    {"en": "rent", "lemma": "nájem", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Platím __________.", "answer": "nájem"},
    {"en": "owner (f)", "lemma": "majitelka", "gender": "fem (žena)", "case": 3, "sentence": "Píšu __________.", "answer": "majitelce"},
    {"en": "neighbor (f)", "lemma": "sousedka", "gender": "fem (žena)", "case": 4, "sentence": "Vidím __________.", "answer": "sousedku"},
    {"en": "roommate", "lemma": "spolubydlící", "gender": "masc_anim (adj/muž)", "case": 7, "sentence": "Mluvím se __________.", "answer": "spolubydlícím"},
    {"en": "room", "lemma": "místnost", "gender": "fem (kost)", "case": 6, "sentence": "V této __________ je klid.", "answer": "místnosti"},
    {"en": "bathroom", "lemma": "koupelna", "gender": "fem (žena)", "case": 6, "sentence": "Jsem v __________.", "answer": "koupelně"},
    {"en": "toilet", "lemma": "záchod", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hledám __________.", "answer": "záchod"},
    {"en": "window", "lemma": "okno", "gender": "neutr (město)", "case": 2, "sentence": "Dívám se z __________.", "answer": "okna"},
    {"en": "corridor", "lemma": "chodba", "gender": "fem (žena)", "case": 6, "sentence": "V __________ je světlo.", "answer": "chodbě"},
    {"en": "stair", "lemma": "schod", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Stojím na __________.", "answer": "schodu"},
    {"en": "furniture", "lemma": "nábytek", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Koupím nový __________.", "answer": "nábytek"},
    {"en": "table", "lemma": "stůl", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Hýbu __________.", "answer": "stolem"},
    {"en": "chair", "lemma": "židle", "gender": "fem (růže)", "case": 4, "sentence": "Chci tuhle __________.", "answer": "židli"},
    {"en": "wardrobe", "lemma": "skříň", "gender": "fem (píseň)", "case": 6, "sentence": "Mám věci ve __________.", "answer": "skříni"},
    {"en": "bed", "lemma": "postel", "gender": "fem (píseň)", "case": 7, "sentence": "Před __________ leží pes.", "answer": "postelí"},
    {"en": "couch", "lemma": "gauč", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Sedím na __________.", "answer": "gauči"},
    {"en": "shower", "lemma": "sprcha", "gender": "fem (žena)", "case": 6, "sentence": "Jsem ve __________.", "answer": "sprše"},
    {"en": "bathtub", "lemma": "vana", "gender": "fem (žena)", "case": 4, "sentence": "Mám velkou __________.", "answer": "vanu"},
    {"en": "washbasin", "lemma": "umyvadlo", "gender": "neutr (město)", "case": 6, "sentence": "Mám mýdlo na __________.", "answer": "umyvadle"},
    {"en": "TV", "lemma": "televize", "gender": "fem (růže)", "case": 4, "sentence": "Sleduju __________.", "answer": "televizi"},
    {"en": "radio", "lemma": "rádio", "gender": "neutr (město)", "case": 4, "sentence": "Poslouchám __________.", "answer": "rádio"},
    {"en": "fridge", "lemma": "lednička", "gender": "fem (žena)", "case": 2, "sentence": "Vezmu to z __________.", "answer": "ledničky"},
    {"en": "washing machine", "lemma": "pračka", "gender": "fem (žena)", "case": 4, "sentence": "Zapnu __________.", "answer": "pračku"},
    {"en": "cooker", "lemma": "sporák", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Vařím na __________.", "answer": "sporáku"},
    {"en": "microwave", "lemma": "mikrovlnka", "gender": "fem (žena)", "case": 4, "sentence": "Mám __________.", "answer": "mikrovlnku"},
    {"en": "lamp", "lemma": "lampa", "gender": "fem (žena)", "case": 7, "sentence": "Čtu pod __________.", "answer": "lampou"},
    {"en": "wall", "lemma": "stěna", "gender": "fem (žena)", "case": 6, "sentence": "Obraz visí na __________.", "answer": "stěně"},

    //# --- ÚŘADY A PRÁVO ---
    {"en": "offence", "lemma": "přestupek", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Udělal jsi __________.", "answer": "přestupek"},
    {"en": "tax", "lemma": "daň", "gender": "fem (píseň)", "case": 4, "sentence": "Platím __________.", "answer": "daň"},
    {"en": "pension", "lemma": "důchod", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Pobírám __________.", "answer": "důchod"},
    {"en": "maternity leave", "lemma": "mateřská", "gender": "fem (adj/žena)", "case": 6, "sentence": "Je na __________.", "answer": "mateřské"},
    {"en": "OAMP", "lemma": "OAMP", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Musím na __________.", "answer": "OAMP"},
    {"en": "residence", "lemma": "pobyt", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Hledám trvalý __________.", "answer": "pobyt"},
    {"en": "extract", "lemma": "výpis", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Potřebuju __________ z banky.", "answer": "výpis"},
    {"en": "theft", "lemma": "krádež", "gender": "fem (píseň)", "case": 4, "sentence": "Nahlásím __________.", "answer": "krádež"},
    {"en": "firefighter", "lemma": "hasič", "gender": "masc_anim (muž)", "case": 3, "sentence": "Děkujeme __________.", "answer": "hasičovi"},
    {"en": "ambulance", "lemma": "záchranka", "gender": "fem (žena)", "case": 4, "sentence": "Zavolejte __________!", "answer": "záchranku"},
    {"en": "danger", "lemma": "nebezpečí", "gender": "neutr (stavení)", "case": 2, "sentence": "Bez __________.", "answer": "nebezpečí"},
    {"en": "fire", "lemma": "požár", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Bojím se __________.", "answer": "požáru"},
    {"en": "flood", "lemma": "povodeň", "gender": "fem (píseň)", "case": 6, "sentence": "Bojíme se __________.", "answer": "povodni"},
    {"en": "crisis", "lemma": "krize", "gender": "fem (růže)", "case": 4, "sentence": "Řešíme __________.", "answer": "krizi"},

    //# --- VZDĚLÁVÁNÍ ---
    {"en": "university", "lemma": "univerzita", "gender": "fem (žena)", "case": 2, "sentence": "Jdu z __________.", "answer": "univerzity"},
    {"en": "course", "lemma": "kurz", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Navštěvuju __________.", "answer": "kurz"},
    {"en": "application", "lemma": "přihláška", "gender": "fem (žena)", "case": 4, "sentence": "Vyplním __________.", "answer": "přihlášku"},
    {"en": "classroom", "lemma": "třída", "gender": "fem (žena)", "case": 6, "sentence": "Učitel je ve __________.", "answer": "třídě"},
    {"en": "cloakroom", "lemma": "šatna", "gender": "fem (žena)", "case": 6, "sentence": "Nechte si věci v __________.", "answer": "šatně"},
    {"en": "gym", "lemma": "tělocvična", "gender": "fem (žena)", "case": 6, "sentence": "Cvičíme v __________.", "answer": "tělocvičně"},
    {"en": "dining room", "lemma": "jídelna", "gender": "fem (žena)", "case": 6, "sentence": "Jíme v __________.", "answer": "jídelně"},
    {"en": "library", "lemma": "knihovna", "gender": "fem (žena)", "case": 2, "sentence": "Jdu do __________.", "answer": "knihovny"},
    {"en": "paper", "lemma": "papír", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Píšu na __________.", "answer": "papír"},
    {"en": "exercise book", "lemma": "sešit", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Otevřete __________.", "answer": "sešit"},
    {"en": "textbook", "lemma": "učebnice", "gender": "fem (růže)", "case": 2, "sentence": "Čtu z __________.", "answer": "učebnice"},
    {"en": "dictionary", "lemma": "slovník", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Hledám to ve __________.", "answer": "slovníku"},
    {"en": "laptop", "lemma": "notebook", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Píšu na __________.", "answer": "notebooku"},
    {"en": "pen", "lemma": "propiska", "gender": "fem (žena)", "case": 7, "sentence": "Píšu modrou __________.", "answer": "propiskou"},
    {"en": "janitor", "lemma": "školník", "gender": "masc_anim (pán)", "case": 4, "sentence": "Zavolám __________.", "answer": "školníka"},
    {"en": "cleaning lady", "lemma": "uklízečka", "gender": "fem (žena)", "case": 3, "sentence": "Pomůžu __________.", "answer": "uklízečce"},
    {"en": "pupil (m)", "lemma": "žák", "gender": "masc_anim (pán)", "case": 2, "sentence": "Vidím nového __________.", "answer": "žáka"},
    {"en": "pupil (f)", "lemma": "žákyně", "gender": "fem (růže)", "case": 3, "sentence": "Vysvětlím to __________.", "answer": "žákyni"},
    {"en": "example", "lemma": "příklad", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Vypočítej __________.", "answer": "příklad"},
    {"en": "assignment", "lemma": "úkol", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám těžký __________.", "answer": "úkol"},
    {"en": "break", "lemma": "přestávka", "gender": "fem (žena)", "case": 6, "sentence": "Mluvíme o __________.", "answer": "přestávce"},
    {"en": "lesson", "lemma": "hodina", "gender": "fem (žena)", "case": 6, "sentence": "Učím se v __________.", "answer": "hodině"},
    {"en": "subject", "lemma": "předmět", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Nemám rád ten __________.", "answer": "předmět"},
    {"en": "Czech", "lemma": "čeština", "gender": "fem (žena)", "case": 4, "sentence": "Mám rád __________.", "answer": "češtinu"},
    {"en": "English", "lemma": "angličtina", "gender": "fem (žena)", "case": 4, "sentence": "Studuju __________.", "answer": "angličtinu"},
    {"en": "mathematics", "lemma": "matematika", "gender": "fem (žena)", "case": 3, "sentence": "Nerozumím __________.", "answer": "matematice"},
    {"en": "physics", "lemma": "fyzika", "gender": "fem (žena)", "case": 2, "sentence": "Bojím se __________.", "answer": "fyziky"},
    {"en": "biology", "lemma": "biologie", "gender": "fem (růže)", "case": 4, "sentence": "Mám __________.", "answer": "biologii"},
    {"en": "chemistry", "lemma": "chemie", "gender": "fem (růže)", "case": 6, "sentence": "Pracuju v __________.", "answer": "chemii"},
    {"en": "geography", "lemma": "zeměpis", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Učím se __________.", "answer": "zeměpis"},
    {"en": "history", "lemma": "dějepis", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Zkouška z __________.", "answer": "dějepisu"},
    {"en": "PE", "lemma": "tělocvik", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Cvičíme v __________.", "answer": "tělocviku"},
    {"en": "field (study)", "lemma": "obor", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám zajímavý __________.", "answer": "obor"},
    {"en": "law", "lemma": "právo", "gender": "neutr (město)", "case": 4, "sentence": "Studuju __________.", "answer": "právo"},
    {"en": "medicine", "lemma": "medicína", "gender": "fem (žena)", "case": 4, "sentence": "Chci studovat __________.", "answer": "medicínu"},
    {"en": "computer sci.", "lemma": "informatika", "gender": "fem (žena)", "case": 4, "sentence": "Mám rád __________.", "answer": "informatiku"},
    {"en": "economic", "lemma": "ekonomie", "gender": "fem (růže)", "case": 2, "sentence": "Základy __________.", "answer": "ekonomie"},
    {"en": "test", "lemma": "test", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Píšu __________.", "answer": "test"},
    {"en": "exam", "lemma": "zkouška", "gender": "fem (žena)", "case": 6, "sentence": "Byl jsem na __________.", "answer": "zkoušce"},
    {"en": "grade", "lemma": "známka", "gender": "fem (žena)", "case": 4, "sentence": "Mám dobrou __________.", "answer": "známku"},
    {"en": "point", "lemma": "bod", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám jeden __________.", "answer": "bod"},
    {"en": "mistake", "lemma": "chyba", "gender": "fem (žena)", "case": 6, "sentence": "V testu je __________.", "answer": "chyba"},
    {"en": "education", "lemma": "vzdělání", "gender": "neutr (stavení)", "case": 4, "sentence": "Mám vysoké __________.", "answer": "vzdělání"},
    {"en": "school report", "lemma": "vysvědčení", "gender": "neutr (stavení)", "case": 4, "sentence": "Dostal jsem __________.", "answer": "vysvědčení"},
    {"en": "leaving exam", "lemma": "maturita", "gender": "fem (žena)", "case": 4, "sentence": "Udělám __________.", "answer": "maturitu"},
    {"en": "university deg.", "lemma": "diplom", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Dostal jsem __________.", "answer": "diplom"},

    //# --- POČASÍ ---
    {"en": "star", "lemma": "hvězda", "gender": "fem (žena)", "case": 4, "sentence": "Vidím __________.", "answer": "hvězdu"},
    {"en": "moon", "lemma": "měsíc", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Sleduju __________.", "answer": "měsíc"},
    {"en": "mountain", "lemma": "hora", "gender": "fem (žena)", "case": 2, "sentence": "Jdu z __________.", "answer": "hory"},
    {"en": "sky", "lemma": "nebe", "gender": "neutr (moře)", "case": 6, "sentence": "Na __________ jsou mraky.", "answer": "nebi"},
    {"en": "river", "lemma": "řeka", "gender": "fem (žena)", "case": 7, "sentence": "Plavu za __________.", "answer": "řekou"},
    {"en": "nature", "lemma": "příroda", "gender": "fem (žena)", "case": 2, "sentence": "Ochrana __________.", "answer": "přírody"},
    {"en": "forest", "lemma": "les", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Jsme v __________.", "answer": "lese"},
    {"en": "field", "lemma": "pole", "gender": "neutr (moře)", "case": 6, "sentence": "Zvířata jsou na __________.", "answer": "poli"},
    {"en": "plant", "lemma": "rostlina", "gender": "fem (žena)", "case": 4, "sentence": "Zaleju __________.", "answer": "rostlinu"},
    {"en": "tree", "lemma": "strom", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Stojím pod __________.", "answer": "stromem"},
    {"en": "lake", "lemma": "jezero", "gender": "neutr (město)", "case": 6, "sentence": "Plavu v __________.", "answer": "jezeře"},
    {"en": "weather", "lemma": "počasí", "gender": "neutr (stavení)", "case": 2, "sentence": "Podle __________.", "answer": "počasí"},
    {"en": "temperature", "lemma": "teplota", "gender": "fem (žena)", "case": 2, "sentence": "Změna __________.", "answer": "teploty"},
    {"en": "sun", "lemma": "slunce", "gender": "neutr (moře)", "case": 4, "sentence": "Vidím __________.", "answer": "slunce"},
    {"en": "cloud", "lemma": "mrak", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Bez __________.", "answer": "mraku"},
    {"en": "wind", "lemma": "vítr", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Bojujeme s __________.", "answer": "větrem"},
    {"en": "storm", "lemma": "bouřka", "gender": "fem (žena)", "case": 6, "sentence": "V __________ se bojím.", "answer": "bouřce"},
    {"en": "fog", "lemma": "mlha", "gender": "fem (žena)", "case": 6, "sentence": "V __________ nic nevidím.", "answer": "mlze"},
    {"en": "forecast", "lemma": "předpověď", "gender": "fem (kost)", "case": 4, "sentence": "Sleduju __________.", "answer": "předpověď"},

    //# --- ZDRAVÍ ---
    {"en": "body", "lemma": "tělo", "gender": "neutr (město)", "case": 4, "sentence": "Cvičím celé __________.", "answer": "tělo"},
    {"en": "head", "lemma": "hlava", "gender": "fem (žena)", "case": 6, "sentence": "Mám to v __________.", "answer": "hlavě"},
    {"en": "nose", "lemma": "nos", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám velký __________.", "answer": "nos"},
    {"en": "ear", "lemma": "ucho", "gender": "neutr (město)", "case": 6, "sentence": "Mám něco v __________.", "answer": "uchu"},
    {"en": "mouth", "lemma": "pusa", "gender": "fem (žena)", "case": 4, "sentence": "Otevři __________.", "answer": "pusu"},
    {"en": "face", "lemma": "obličej", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Mám čistý __________.", "answer": "obličej"},
    {"en": "tongue", "lemma": "jazyk", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Ukažte __________.", "answer": "jazyk"},
    {"en": "neck", "lemma": "krk", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Bolí mě v __________.", "answer": "krku"},
    {"en": "finger", "lemma": "prst", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Hýbu __________.", "answer": "prstem"},
    {"en": "back", "lemma": "záda", "gender": "neutr (město - pl)", "case": 4, "sentence": "Bolí mě __________.", "answer": "záda"},
    {"en": "belly", "lemma": "břicho", "gender": "neutr (město)", "case": 4, "sentence": "Mám velké __________.", "answer": "břicho"},
    {"en": "stomach", "lemma": "žaludek", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Bolest __________.", "answer": "žaludku"},
    {"en": "skin", "lemma": "kůže", "gender": "fem (růže)", "case": 4, "sentence": "Mám jemnou __________.", "answer": "kůži"},
    {"en": "runny nose", "lemma": "rýma", "gender": "fem (žena)", "case": 4, "sentence": "Mám silnou __________.", "answer": "rýmu"},
    {"en": "cough", "lemma": "kašel", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Mám suchý __________.", "answer": "kašel"},
    {"en": "diarrhea", "lemma": "průjem", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám __________.", "answer": "průjem"},
    {"en": "constipation", "lemma": "zácpa", "gender": "fem (žena)", "case": 2, "sentence": "Bojím se __________.", "answer": "zácpy"},
    {"en": "pressure", "lemma": "tlak", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Měřím si __________.", "answer": "tlak"},
    {"en": "wound", "lemma": "rána", "gender": "fem (žena)", "case": 6, "sentence": "Sůl v __________.", "answer": "ráně"},
    {"en": "injury", "lemma": "úraz", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Měl jsem vážný __________.", "answer": "úraz"},
    {"en": "examination", "lemma": "vyšetření", "gender": "neutr (stavení)", "case": 4, "sentence": "Potřebuju __________.", "answer": "vyšetření"},
    {"en": "allergy", "lemma": "alergie", "gender": "fem (růže)", "case": 4, "sentence": "Mám __________.", "answer": "alergii"},
    {"en": "diet", "lemma": "dieta", "gender": "fem (žena)", "case": 4, "sentence": "Držím __________.", "answer": "dietu"},
    {"en": "flu", "lemma": "chřipka", "gender": "fem (žena)", "case": 6, "sentence": "Ležím s __________.", "answer": "chřipkou"},
    {"en": "the practice", "lemma": "ordinace", "gender": "fem (růže)", "case": 6, "sentence": "Jsem v __________.", "answer": "ordinaci"},
    {"en": "waiting room", "lemma": "čekárna", "gender": "fem (žena)", "case": 6, "sentence": "Sedím v __________.", "answer": "čekárně"},
    {"en": "emergency", "lemma": "pohotovost", "gender": "fem (kost)", "case": 4, "sentence": "Hledám __________.", "answer": "pohotovost"},
    {"en": "vaccination", "lemma": "očkování", "gender": "neutr (stavení)", "case": 6, "sentence": "Byl jsem na __________.", "answer": "očkování"},
    {"en": "recept", "lemma": "recept", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Napíšu vám __________.", "answer": "recept"},
    {"en": "insurance", "lemma": "pojištění", "gender": "neutr (stavení)", "case": 4, "sentence": "Mám zdravotní __________.", "answer": "pojištění"},

    //# --- SPOLEČNOST ---
    {"en": "beginner (m)", "lemma": "začátečník", "gender": "masc_anim (pán)", "case": 4, "sentence": "Učím __________.", "answer": "začátečníka"},
    {"en": "beginner (f)", "lemma": "začátečnice", "gender": "fem (růže)", "case": 2, "sentence": "Třída pro __________.", "answer": "začátečnice"},
    {"en": "acquaintance", "lemma": "známý", "gender": "masc_anim (adj/muž)", "case": 7, "sentence": "Mluvím se __________.", "answer": "známým"},
    {"en": "guest", "lemma": "host", "gender": "masc_anim (kost - nepravidelný)", "case": 4, "sentence": "Vítám __________.", "answer": "hosta"},
    {"en": "foreigner (m)", "lemma": "cizinec", "gender": "masc_anim (muž)", "case": 2, "sentence": "Hledám __________.", "answer": "cizince"},
    {"en": "foreigner (f)", "lemma": "cizinka", "gender": "fem (žena)", "case": 6, "sentence": "Mluvím o té __________.", "answer": "cizince"},
    {"en": "society", "lemma": "společnost", "gender": "fem (kost)", "case": 6, "sentence": "Žijeme ve __________.", "answer": "společnosti"},
    {"en": "government", "lemma": "vláda", "gender": "fem (žena)", "case": 3, "sentence": "Věřím __________.", "answer": "vládě"},
    {"en": "ministry", "lemma": "ministerstvo", "gender": "neutr (město)", "case": 2, "sentence": "Dopis z __________.", "answer": "ministerstva"},
    {"en": "parliament", "lemma": "parlament", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Mluví se v __________.", "answer": "parlamentu"},
    {"en": "Senate", "lemma": "Senát", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Jsme v __________.", "answer": "Senátu"},
    {"en": "political party", "lemma": "strana", "gender": "fem (žena)", "case": 4, "sentence": "Volím tuhle __________.", "answer": "stranu"},
    {"en": "elections", "lemma": "volby", "gender": "fem (žena - pl)", "case": 6, "sentence": "O __________ se nemluví.", "answer": "volbách"},
    {"en": "village", "lemma": "vesnice", "gender": "fem (růže)", "case": 2, "sentence": "Jdu z __________.", "answer": "vesnice"},
    {"en": "region", "lemma": "kraj", "gender": "masc_inan (stroj)", "case": 6, "sentence": "Bydlím v tomto __________.", "answer": "kraji"},

    //# --- TECHNOLOGIE A OSTATNÍ ---
    {"en": "charger", "lemma": "nabíječka", "gender": "fem (žena)", "case": 4, "sentence": "Hledám __________.", "answer": "nabíječku"},
    {"en": "password", "lemma": "heslo", "gender": "neutr (město)", "case": 4, "sentence": "Zapomněl jsem __________.", "answer": "heslo"},
    {"en": "attachment", "lemma": "příloha", "gender": "fem (žena)", "case": 6, "sentence": "Vidím to v __________.", "answer": "příloze"},
    {"en": "signal", "lemma": "signál", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Nemám __________.", "answer": "signál"},
    {"en": "opinion", "lemma": "názor", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Mám jiný __________.", "answer": "názor"},
    {"en": "difference", "lemma": "rozdíl", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Vidím __________.", "answer": "rozdíl"},
    {"en": "opportunity", "lemma": "možnost", "gender": "fem (kost)", "case": 4, "sentence": "Mám novou __________.", "answer": "možnost"},
    {"en": "contract", "lemma": "smlouva", "gender": "fem (žena)", "case": 7, "sentence": "Souhlasím se __________.", "answer": "smlouvou"},
    {"en": "stamp", "lemma": "razítko", "gender": "neutr (město)", "case": 4, "sentence": "Chci __________.", "answer": "razítko"},
    {"en": "wolf", "lemma": "vlk", "gender": "masc_anim (pán)", "case": 2, "sentence": "Bojím se __________.", "answer": "vlka"},
    {"en": "bear", "lemma": "medvěd", "gender": "masc_anim (pán)", "case": 4, "sentence": "Vidím __________.", "answer": "medvěda"},
    {"en": "bird", "lemma": "pták", "gender": "masc_anim (pán)", "case": 4, "sentence": "Sleduju __________.", "answer": "ptáka"},

    //# --- DOPLNĚK DO 300 (opakovací věty s variacemi) ---
    {"en": "year", "lemma": "rok", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Do konce __________.", "answer": "roku"},
    {"en": "hand", "lemma": "ruka", "gender": "fem (žena)", "case": 4, "sentence": "Podej mi __________.", "answer": "ruku"},
    {"en": "city", "lemma": "město", "gender": "neutr (město)", "case": 3, "sentence": "Díky tomuto __________.", "answer": "městu"},
    {"en": "castle", "lemma": "hrad", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Navštívíme __________.", "answer": "hrad"},
    {"en": "chair", "lemma": "židle", "gender": "fem (růže)", "case": 2, "sentence": "Sedím bez __________.", "answer": "židle"},
    {"en": "window", "lemma": "okno", "gender": "neutr (město)", "case": 6, "sentence": "O __________ se opírá kočka.", "answer": "okně"},
    {"en": "soup", "lemma": "polévka", "gender": "fem (žena)", "case": 7, "sentence": "S tou __________ jsem spokojen.", "answer": "polévkou"},
    {"en": "shop assistant (m)", "lemma": "prodavač", "gender": "masc_anim (pán)", "case": 3, "sentence": "Řeknu to __________.", "answer": "prodavačovi"},
    {"en": "bill", "lemma": "účet", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Vše je na __________.", "answer": "účtu"},
    {"en": "tea", "lemma": "čaj", "gender": "masc_inan (stroj)", "case": 2, "sentence": "Bez __________.", "answer": "čaje"},
    {"en": "coffee", "lemma": "káva", "gender": "fem (žena)", "case": 2, "sentence": "Šálek horké __________.", "answer": "kávy"},
    {"en": "friend (male)", "lemma": "kamarád", "gender": "masc_anim (pán)", "case": 3, "sentence": "Půjčím to __________.", "answer": "kamarádovi"},
    {"en": "friend (female)", "lemma": "kamarádka", "gender": "fem (žena)", "case": 7, "sentence": "Jdu do kina s __________.", "answer": "kamarádkou"},
    {"en": "car", "lemma": "auto", "gender": "neutr (město)", "case": 2, "sentence": "Vystoupil z __________.", "answer": "auta"},
    {"en": "house", "lemma": "dům", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Bydlí v novém __________.", "answer": "domě"},
    {"en": "street", "lemma": "ulice", "gender": "fem (růže)", "case": 6, "sentence": "Stojím na __________.", "answer": "ulici"},
    {"en": "beer", "lemma": "pivo", "gender": "neutr (město)", "case": 7, "sentence": "Zapijeme to __________.", "answer": "pivem"},
    {"en": "wine", "lemma": "víno", "gender": "neutr (město)", "case": 3, "sentence": "Nerozumím dobrému __________.", "answer": "vínu"},
    {"en": "check / bill", "lemma": "účet", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Zaplatím __________.", "answer": "účet"},
    {"en": "person", "lemma": "člověk", "gender": "masc_anim (pán)", "case": 7, "sentence": "Mluvil jsem s jedním __________.", "answer": "člověkem"},
    {"en": "mother", "lemma": "matka", "gender": "fem (žena)", "case": 3, "sentence": "Pomáhám své __________.", "answer": "matce"},
    {"en": "father", "lemma": "otec", "gender": "masc_anim (muž)", "case": 4, "sentence": "Navštívím __________.", "answer": "otce"},
    {"en": "son", "lemma": "syn", "gender": "masc_anim (pán)", "case": 2, "sentence": "Hračka mého __________.", "answer": "syna"},
    {"en": "daughter", "lemma": "dcera", "gender": "fem (žena)", "case": 7, "sentence": "Jdu ven se svou __________.", "answer": "dcerou"},
    {"en": "brother", "lemma": "bratr", "gender": "masc_anim (pán)", "case": 6, "sentence": "Mluvím o svém __________.", "answer": "bratrovi"},
    {"en": "sister", "lemma": "sestra", "gender": "fem (žena)", "case": 3, "sentence": "Zavolám své __________.", "answer": "sestře"},
    {"en": "room", "lemma": "pokoj", "gender": "masc_inan (stroj)", "case": 6, "sentence": "Uklízím v __________.", "answer": "pokoji"},
    {"en": "apartment", "lemma": "byt", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Klíče od __________.", "answer": "bytu"},
    {"en": "water", "lemma": "voda", "gender": "fem (žena)", "case": 7, "sentence": "Umeju si ruce __________.", "answer": "vodou"},
    {"en": "shop", "lemma": "obchod", "gender": "masc_inan (hrad)", "case": 3, "sentence": "Blížíme se k __________.", "answer": "obchodu"},
    {"en": "food", "lemma": "jídlo", "gender": "neutr (město)", "case": 4, "sentence": "Máš rád české __________?", "answer": "jídlo"},
    {"en": "bread", "lemma": "chleba", "gender": "masc_inan (hrad/nepravidelný)", "case": 2, "sentence": "Kousek __________.", "answer": "chleba"},
    {"en": "roll", "lemma": "rohlík", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Koupím jeden __________.", "answer": "rohlík"},
    {"en": "apple", "lemma": "jablko", "gender": "neutr (město)", "case": 7, "sentence": "Snídaně s __________.", "answer": "jablkem"},
    {"en": "meat", "lemma": "maso", "gender": "neutr (město)", "case": 2, "sentence": "Jím hodně __________.", "answer": "masa"},
    {"en": "milk", "lemma": "mléko", "gender": "neutr (město)", "case": 4, "sentence": "Piju studené __________.", "answer": "mléko"},
    {"en": "cheese", "lemma": "sýr", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Chleba se __________.", "answer": "sýrem"},
    {"en": "butter", "lemma": "máslo", "gender": "neutr (město)", "case": 2, "sentence": "Bez __________ to není dobré.", "answer": "másla"},
    {"en": "sugar", "lemma": "cukr", "gender": "masc_inan (hrad)", "case": 3, "sentence": "Odpor k __________.", "answer": "cukru"},
    {"en": "salt", "lemma": "sůl", "gender": "fem (kost)", "case": 4, "sentence": "Podej mi __________.", "answer": "sůl"},
    {"en": "egg", "lemma": "vejce", "gender": "neutr (moře)", "case": 2, "sentence": "Smažím to bez __________.", "answer": "vajec"},
    {"en": "chicken", "lemma": "kuře", "gender": "neutr (kuře)", "case": 2, "sentence": "Stehno z __________.", "answer": "kuřete"},
    {"en": "job / work", "lemma": "práce", "gender": "fem (růže)", "case": 4, "sentence": "Mám těžkou __________.", "answer": "práci"},
    {"en": "money", "lemma": "peníze", "gender": "masc_inan (stroj - pl)", "case": 7, "sentence": "Platím hotovými __________.", "answer": "penězi"},
    {"en": "time", "lemma": "čas", "gender": "masc_inan (stroj)", "case": 4, "sentence": "Máš __________?", "answer": "čas"},
    {"en": "day", "lemma": "den", "gender": "masc_inan (stroj)", "case": 3, "sentence": "Díky tomuto __________.", "answer": "dni"},
    {"en": "night", "lemma": "noc", "gender": "fem (kost)", "case": 6, "sentence": "V __________ je tma.", "answer": "noci"},
    {"en": "morning", "lemma": "ráno", "gender": "neutr (město)", "case": 4, "sentence": "Mám rád klidné __________.", "answer": "ráno"},
    {"en": "evening", "lemma": "večer", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Před __________ se projdu.", "answer": "večerem"},
    {"en": "week", "lemma": "týden", "gender": "masc_inan (stroj)", "case": 2, "sentence": "Během __________.", "answer": "týdne"},
    {"en": "month", "lemma": "měsíc", "gender": "masc_inan (stroj)", "case": 6, "sentence": "V tomto __________.", "answer": "měsíci"},
    {"en": "school", "lemma": "škola", "gender": "fem (žena)", "case": 2, "sentence": "Jdu ze __________.", "answer": "školy"},
    {"en": "student (male)", "lemma": "student", "gender": "masc_anim (pán)", "case": 4, "sentence": "Vidím nového __________.", "answer": "studenta"},
    {"en": "teacher (male)", "lemma": "učitel", "gender": "masc_anim (muž)", "case": 3, "sentence": "Poděkuji __________.", "answer": "učiteli"},
    {"en": "book", "lemma": "kniha", "gender": "fem (žena)", "case": 7, "sentence": "Listuju starou __________.", "answer": "knihou"},
    {"en": "lesson", "lemma": "lekce", "gender": "fem (růže)", "case": 4, "sentence": "Máme těžkou __________.", "answer": "lekci"},
    {"en": "word", "lemma": "slovo", "gender": "neutr (město)", "case": 2, "sentence": "Bez jediného __________.", "answer": "slova"},
    {"en": "help", "lemma": "pomoc", "gender": "fem (kost)", "case": 4, "sentence": "Potřebuju __________.", "answer": "pomoc"},
    {"en": "problem", "lemma": "problém", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Máme malý __________.", "answer": "problém"},
    {"en": "question", "lemma": "otázka", "gender": "fem (žena)", "case": 4, "sentence": "Mám jednu __________.", "answer": "otázku"},
    {"en": "answer", "lemma": "odpověď", "gender": "fem (kost)", "case": 3, "sentence": "K této __________.", "answer": "odpovědi"},
    {"en": "table", "lemma": "stůl", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Váza je na __________.", "answer": "stole"},
    {"en": "chair", "lemma": "židle", "gender": "fem (růže)", "case": 7, "sentence": "Hýbu tou __________.", "answer": "židlí"},
    {"en": "bag", "lemma": "taška", "gender": "fem (žena)", "case": 4, "sentence": "Nesu těžkou __________.", "answer": "tašku"},
    {"en": "suitcase", "lemma": "kufr", "gender": "masc_inan (hrad)", "case": 7, "sentence": "Jedu s velkým __________.", "answer": "kufrem"},
    {"en": "train", "lemma": "vlak", "gender": "masc_inan (hrad)", "case": 2, "sentence": "Vystoupil z __________.", "answer": "vlaku"},
    {"en": "bus", "lemma": "autobus", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Jsem v __________.", "answer": "autobusu"},
    {"en": "airport", "lemma": "letiště", "gender": "neutr (moře)", "case": 6, "sentence": "Čekám na __________.", "answer": "letišti"},
    {"en": "station", "lemma": "nádraží", "gender": "neutr (stavení)", "case": 2, "sentence": "Jdu z __________.", "answer": "nádraží"},
    {"en": "trip / tour", "lemma": "zájezd", "gender": "masc_inan (hrad)", "case": 4, "sentence": "Koupil jsem __________.", "answer": "zájezd"},
    {"en": "nature", "lemma": "příroda", "gender": "fem (žena)", "case": 6, "sentence": "Jsme v __________.", "answer": "přírodě"},
    {"en": "tree", "lemma": "strom", "gender": "masc_inan (hrad)", "case": 2, "sentence": "List ze __________.", "answer": "stromu"},
    {"en": "flower", "lemma": "květina", "gender": "fem (žena)", "case": 4, "sentence": "Koupím krásnou __________.", "answer": "květinu"},
    {"en": "sun", "lemma": "slunce", "gender": "neutr (moře)", "case": 2, "sentence": "Bez __________.", "answer": "slunce"},
    {"en": "rain", "lemma": "déšť", "gender": "masc_inan (stroj)", "case": 7, "sentence": "Běžím před __________.", "answer": "deštěm"},
    {"en": "snow", "lemma": "sníh", "gender": "masc_inan (hrad)", "case": 6, "sentence": "Děti si hrají ve __________.", "answer": "sněhu"},
    {"en": "weather", "lemma": "počasí", "gender": "neutr (stavení)", "case": 4, "sentence": "Sleduju __________.", "answer": "počasí"},
    {"en": "health", "lemma": "zdraví", "gender": "neutr (stavení)", "case": 2, "sentence": "Přeju hodně __________.", "answer": "zdraví"},
    {"en": "happiness / luck", "lemma": "štěstí", "gender": "neutr (stavení)", "case": 4, "sentence": "Přeju hodně __________.", "answer": "štěstí"},
    {"en": "love", "lemma": "láska", "gender": "fem (žena)", "case": 7, "sentence": "Mluvím o __________.", "answer": "lásce"},
]