
// nouns.js
const fullDatabase = [
    {cz:"člověk",pattern:"pán",en:"person"},{cz:"pán",pattern:"pán",en:"sir"},{cz:"muž",pattern:"muž",en:"man"},
    {cz:"žena",pattern:"žena",en:"woman"},{cz:"růže",pattern:"růže",en:"rose"},{cz:"město",pattern:"město",en:"city"},
    {cz:"moře",pattern:"moře",en:"sea"},{cz:"dům",pattern:"hrad",en:"house"},{cz:"hrad",pattern:"hrad",en:"castle"},
    {cz:"stroj",pattern:"stroj",en:"machine"},{cz:"předseda",pattern:"předseda",en:"chairman"},
    {cz:"soudce",pattern:"soudce",en:"judge"},{cz:"píseň",pattern:"píseň",en:"song"},{cz:"kost",pattern:"kost",en:"bone"},
    {cz:"kuře",pattern:"kuře",en:"chicken"},{cz:"stavení",pattern:"stavení",en:"building"},{cz:"rok",pattern:"hrad",en:"year"},
    {cz:"ruka",pattern:"žena",en:"hand"},{cz:"dítě",pattern:"kuře",en:"child"},{cz:"cesta",pattern:"žena",en:"way"},
    {cz:"pivo",pattern:"město",en:"beer"},{cz:"voda",pattern:"žena",en:"water"},{cz:"rýže",pattern:"růže",en:"rice"},
    {cz:"losos",pattern:"pán",en:"salmon"},{cz:"úhoř",pattern:"muž",en:"eel"},{cz:"cukr",pattern:"hrad",en:"sugar"},
    {cz:"čaj",pattern:"stroj",en:"tea"},{cz:"autobus",pattern:"hrad",en:"bus"},{cz:"letadlo",pattern:"město",en:"plane"},
    {cz:"tužka",pattern:"žena",en:"pencil"},{cz:"mýdlo",pattern:"město",en:"soap"},{cz:"lžička",pattern:"žena",en:"spoon"},
    {cz:"auto",pattern:"město",en:"car"},{cz:"jachta",pattern:"žena",en:"yacht"},{cz:"práce",pattern:"růže",en:"work/job"},
    {cz:"přístroj",pattern:"stroj",en:"device/instrument"},{cz:"kamarád",pattern:"pán",en:"friend (male)"},
    {cz:"přítel",pattern:"muž",en:"boyfriend/friend"},{cz:"dáreknoun",pattern:"hrad",en:"gift / present"},
    {cz:"volno",pattern:"město",en:"time off / free time"},{cz:"posilovna",pattern:"žena",en:"gym"},
    {cz:"galerie",pattern:"růže",en:"gallery"},{cz:"víkend",pattern:"hrad",en:"weekend"},
    {cz:"počítač",pattern:"stroj",en:"computer"},{cz:"trenér",pattern:"pán",en:"coach / trainer"},
    {cz:"kouč",pattern:"muž",en:"coach"},{cz:"škola",pattern:"žena",en:"school"},{cz:"moře",pattern:"moře",en:"sea"},
    {cz:"pláž",pattern:"píseň",en:"beach"},{cz:"pošta",pattern:"žena",en:"post office"},{cz:"okno",pattern:"město",en:"window"},
    {cz:"květina",pattern:"žena",en:"flower"},{cz:"koupelna",pattern:"žena",en:"bathroom"},
    {cz:"zrcadlo",pattern:"město",en:"mirror"},{cz:"ložnice",pattern:"růže",en:"bedroom"},
    {cz:"postel",pattern:"píseň",en:"bed"},{cz:"byt",pattern:"hrad",en:"flat / apartment"},
    {cz:"pokoj",pattern:"stroj",en:"room"},{cz:"hračka",pattern:"žena",en:"toy"},{cz:"soused",pattern:"pán",en:"neighbor"},
    {cz:"majitel",pattern:"muž",en:"owner"},{cz:"vejce",pattern:"moře",en:"egg"},{cz:"jméno",pattern:"město",en:"name"},
    {cz:"příjmení",pattern:"stavení",en:"surname"},{cz:"pan",pattern:"pán",en:"Mr."},{cz:"paní",pattern:"píseň",en:"Mrs."},
    {cz:"slečna",pattern:"žena",en:"Ms"},{cz:"adresa",pattern:"žena",en:"address"},{cz:"stát",pattern:"hrad",en:"state / country"},
    {cz:"ulice",pattern:"růže",en:"street"},{cz:"číslo",pattern:"město",en:"number"},{cz:"PSČ",pattern:"(abbr)",en:"zip code"},
    {cz:"zavináč",pattern:"muž",en:"@"},{cz:"věk",pattern:"hrad",en:"age"},{cz:"pohlaví",pattern:"stavení",en:"gender"},
    {cz:"kluk",pattern:"pán",en:"boy"},{cz:"holka",pattern:"žena",en:"girl"},{cz:"manžel",pattern:"pán",en:"husband"},
    {cz:"manželka",pattern:"žena",en:"wife"},{cz:"přítelkyně",pattern:"růže",en:"girlfriend"},
    {cz:"partner",pattern:"pán",en:"partner"},{cz:"partnerka",pattern:"žena",en:"partner (f)"},
    {cz:"sňatek",pattern:"hrad",en:"marriage"},{cz:"svatba",pattern:"žena",en:"wedding"},
    {cz:"národnost",pattern:"kost",en:"nationality"},{cz:"občanství",pattern:"stavení",en:"citizenship"},
    {cz:"náboženství",pattern:"stavení",en:"religion"},{cz:"křesťan",pattern:"pán",en:"Christian"},
    {cz:"muslim",pattern:"pán",en:"Muslim"},{cz:"muslimka",pattern:"žena",en:"Muslim (f)"},
    {cz:"ateista",pattern:"předseda",en:"atheist"},{cz:"kostel",pattern:"hrad",en:"church"},
    {cz:"mešita",pattern:"žena",en:"mosque"},{cz:"chrám",pattern:"hrad",en:"temple"},{cz:"pas",pattern:"hrad",en:"passport"},
    {cz:"vízum",pattern:"město",en:"visa"},{cz:"podpis",pattern:"hrad",en:"signature"},{cz:"rodina",pattern:"žena",en:"family"},
    {cz:"rodič",pattern:"pán",en:"parent"},{cz:"matka",pattern:"žena",en:"mother"},{cz:"maminka",pattern:"žena",en:"mom"},
    {cz:"máma",pattern:"žena",en:"mother (col.)"},{cz:"otec",pattern:"muž",en:"father"},
    {cz:"tatínek",pattern:"pán",en:"dad"},{cz:"táta",pattern:"předseda",en:"father (col.)"},
    {cz:"děti",pattern:"kost",en:"children"},{cz:"syn",pattern:"pán",en:"son"},{cz:"dcera",pattern:"žena",en:"daughter"},
    {cz:"bratr",pattern:"pán",en:"brother"},{cz:"sestra",pattern:"žena",en:"sister"},
    {cz:"bratranec",pattern:"muž",en:"male cousin"},{cz:"sestřenice",pattern:"růže",en:"female cousin"},
    {cz:"babička",pattern:"žena",en:"grandma"},{cz:"dědeček",pattern:"pán",en:"grandpa"},
    {cz:"děda",pattern:"předseda",en:"grandpa (col.)"},{cz:"strýc",pattern:"muž",en:"uncle"},
    {cz:"strejda",pattern:"předseda",en:"uncle (col.)"},{cz:"teta",pattern:"žena",en:"aunt"},
    {cz:"brýle",pattern:"růže",en:"glasses"},{cz:"oko",pattern:"město",en:"eye"},{cz:"vlas",pattern:"hrad",en:"hair"},
    {cz:"obchod",pattern:"hrad",en:"shop, store"},{cz:"supermarket",pattern:"hrad",en:"supermarket"},
    {cz:"pekařství",pattern:"stavení",en:"bakery"},{cz:"cukrárna",pattern:"žena",en:"sweet shop"},
    {cz:"řeznictví",pattern:"stavení",en:"butcher shop"},{cz:"papírnictví",pattern:"stavení",en:"stationary store"},
    {cz:"lékárna",pattern:"žena",en:"pharmacy"},{cz:"drogerie",pattern:"růže",en:"drug store"},
    {cz:"trh",pattern:"hrad",en:"market"},{cz:"potraviny",pattern:"hrad",en:"grocery store"},
    {cz:"oblečení",pattern:"stavení",en:"clothing"},{cz:"boty",pattern:"žena",en:"shoes"},
    {cz:"nádobí",pattern:"stavení",en:"dishes"},{cz:"bunda",pattern:"žena",en:"jacket"},
    {cz:"košile",pattern:"růže",en:"shirt"},{cz:"kalhoty",pattern:"žena",en:"trousers"},
    {cz:"džíny",pattern:"(inv)",en:"jeans"},{cz:"tričko",pattern:"město",en:"t-shirt"},
    {cz:"svetr",pattern:"hrad",en:"sweater"},{cz:"šaty",pattern:"hrad",en:"dress"},{cz:"sukně",pattern:"růže",en:"skirt"},
    {cz:"ponožky",pattern:"žena",en:"socks"},{cz:"čepice",pattern:"růže",en:"cap"},{cz:"šátek",pattern:"hrad",en:"scarf"},
    {cz:"šála",pattern:"žena",en:"scarf"},{cz:"rukavice",pattern:"růže",en:"gloves"},
    {cz:"deštník",pattern:"hrad",en:"umbrella"},{cz:"batoh",pattern:"hrad",en:"backpack"},
    {cz:"kabelka",pattern:"žena",en:"handbag"},{cz:"taška",pattern:"žena",en:"bag"},{cz:"cena",pattern:"žena",en:"price"},
    {cz:"sleva",pattern:"žena",en:"discount"},{cz:"kabinka",pattern:"žena",en:"changing room"},
    {cz:"velikost",pattern:"kost",en:"size"},{cz:"barva",pattern:"žena",en:"color"},
    {cz:"předpis",pattern:"hrad",en:"prescription"},{cz:"prášek",pattern:"hrad",en:"pill"},
    {cz:"pokladna",pattern:"žena",en:"cash desk"},{cz:"karta",pattern:"žena",en:"card"},
    {cz:"peníze",pattern:"stroj",en:"money"},{cz:"účtenka",pattern:"žena",en:"receipt"},
    {cz:"služba",pattern:"žena",en:"service"},{cz:"čistírna",pattern:"žena",en:"dry cleaners"},
    {cz:"prádelna",pattern:"žena",en:"launderette"},{cz:"kadeřnictví",pattern:"stavení",en:"hairdresser’s"},
    {cz:"půjčovna",pattern:"žena",en:"rental"},{cz:"směnárna",pattern:"žena",en:"exchange office"},
    {cz:"prodavač",pattern:"pán",en:"shop assistant"},{cz:"prodavačka",pattern:"žena",en:"shop assistant(f)"},
    {cz:"pokladní",pattern:"(inv)",en:"cashier"},{cz:"známka",pattern:"žena",en:"stamp"},
    {cz:"dopis",pattern:"hrad",en:"letter"},{cz:"pohled",pattern:"hrad",en:"postcard"},
    {cz:"balík",pattern:"hrad",en:"package"},{cz:"banka",pattern:"žena",en:"bank"},
    {cz:"bankomat",pattern:"hrad",en:"ATM"},{cz:"účet",pattern:"hrad",en:"bank account"},
    {cz:"měna",pattern:"žena",en:"currency"},{cz:"kurz",pattern:"hrad",en:"exchange rate"},
    {cz:"poplatek",pattern:"hrad",en:"fee, charge"},{cz:"šampon",pattern:"hrad",en:"shampoo"},
    {cz:"ručník",pattern:"hrad",en:"towel"},{cz:"krém",pattern:"hrad",en:"creme"},
    {cz:"hřeben",pattern:"stroj",en:"comb"},{cz:"fén",pattern:"hrad",en:"hairdryer"},
    {cz:"kartáč",pattern:"stroj",en:"brush"},{cz:"kapesník",pattern:"hrad",en:"handkerchief"},
    {cz:"žehlička",pattern:"žena",en:"an iron"},{cz:"vysavač",pattern:"hrad",en:"vacuum cleaner"},
    {cz:"jízdné",pattern:"stavení",en:"fare"},{cz:"jízdenka",pattern:"žena",en:"ticket"},
    {cz:"rezervace",pattern:"růže",en:"reservation"},{cz:"cestující",pattern:"(adj)",en:"passenger"},
    {cz:"destinace",pattern:"růže",en:"destination"},{cz:"itinerář",pattern:"stroj",en:"itinerary"},
    {cz:"cesta",pattern:"žena",en:"journey"},{cz:"dovolená",pattern:"(adj)",en:"holiday"},
    {cz:"prázdniny",pattern:"žena",en:"holidays"},{cz:"zpoždění",pattern:"stavení",en:"delay"},
    {cz:"zavazadlo",pattern:"město",en:"luggage"},{cz:"kufr",pattern:"hrad",en:"suitcase"},
    {cz:"mapa",pattern:"žena",en:"map"},{cz:"nádraží",pattern:"stavení",en:"station"},
    {cz:"svíčková",pattern:"(adj)",en:"beef sirloin"},{cz:"snídaně",pattern:"růže",en:"breakfast"},
    {cz:"zelí",pattern:"stavení",en:"cabbage"},{cz:"kuře",pattern:"kuře",en:"chicken"},
    {cz:"káva",pattern:"žena",en:"coffee"},{cz:"moučník",pattern:"hrad",en:"dessert"},
    {cz:"večeře",pattern:"růže",en:"dinner"},{cz:"nápoj",pattern:"hrad",en:"drink"},
    {cz:"knedlík",pattern:"hrad",en:"dumpling"},{cz:"ryba",pattern:"žena",en:"fish"},
    {cz:"hranolky",pattern:"hrad",en:"French fries"},{cz:"ovoce",pattern:"růže",en:"fruit"},
    {cz:"zmrzlina",pattern:"žena",en:"ice-cream"},{cz:"oběd",pattern:"hrad",en:"lunch"},
    {cz:"ubrousek",pattern:"hrad",en:"napkin"},{cz:"těstoviny",pattern:"žena",en:"pasta"},
    {cz:"brambory",pattern:"hrad",en:"potatoes"},{cz:"restaurace",pattern:"růže",en:"restaurant"},
    {cz:"salát",pattern:"hrad",en:"salad"},{cz:"omáčka",pattern:"žena",en:"sauce"},
    {cz:"kyselé zelí",pattern:"stavení",en:"sauerkraut"},{cz:"příloha",pattern:"žena",en:"side dish"},
    {cz:"polévka",pattern:"žena",en:"soup"},{cz:"propitné",pattern:"(adj)",en:"tip (in restaurant)"},
    {cz:"zelenina",pattern:"žena",en:"vegetables"},{cz:"víno",pattern:"město",en:"wine"},
    {cz:"servírka",pattern:"žena",en:"waitress"},{cz:"číšník",pattern:"pán",en:"waiter"},
    {cz:"kuchař",pattern:"muž",en:"chef"},{cz:"kavárna",pattern:"žena",en:"cafe"},
    {cz:"objednávka",pattern:"žena",en:"order"},{cz:"zaměstnání",pattern:"stavení",en:"employment"},
    {cz:"povolání",pattern:"stavení",en:"occupation"},{cz:"dělník",pattern:"pán",en:"labourer"},
    {cz:"dělnice",pattern:"růže",en:"labourer (f)"},{cz:"řidič",pattern:"muž",en:"driver"},
    {cz:"řidička",pattern:"žena",en:"driver (f)"},{cz:"číšnice",pattern:"růže",en:"waitress"},
    {cz:"kadeřník",pattern:"pán",en:"hairdresser"},{cz:"kadeřnice",pattern:"růže",en:"hairdresser (f)"},
    {cz:"úředník",pattern:"pán",en:"clerk"},{cz:"úřednice",pattern:"růže",en:"clerk (f)"},
    {cz:"účetní",pattern:"(adj)",en:"accountant"},{cz:"lékař",pattern:"muž",en:"doctor"},
    {cz:"lékařka",pattern:"žena",en:"doctor (f)"},{cz:"učitel",pattern:"muž",en:"teacher"},
    {cz:"učitelka",pattern:"žena",en:"teacher (f)"},{cz:"právník",pattern:"pán",en:"lawyer"},
    {cz:"právnička",pattern:"žena",en:"lawyer (f)"},{cz:"soudkyně",pattern:"růže",en:"judge (f)"},
    {cz:"policista",pattern:"předseda",en:"policeman"},{cz:"policistka",pattern:"žena",en:"policewoman"},
    {cz:"novinář",pattern:"muž",en:"journalist"},{cz:"novinářka",pattern:"žena",en:"journalist (f)"},
    {cz:"podnikatel",pattern:"muž",en:"businessman"},{cz:"podnikatelka",pattern:"žena",en:"businesswoman"},
    {cz:"studentka",pattern:"žena",en:"student (f)"},{cz:"pracoviště",pattern:"moře",en:"workplace"},
    {cz:"továrna",pattern:"žena",en:"factory"},{cz:"podnik",pattern:"hrad",en:"enterprise"},
    {cz:"stavba",pattern:"žena",en:"construction"},{cz:"firma",pattern:"žena",en:"company"},
    {cz:"úřad",pattern:"hrad",en:"office"},{cz:"farma",pattern:"žena",en:"farm"},
    {cz:"nemocnice",pattern:"růže",en:"hospital"},{cz:"zaměstnavatel",pattern:"muž",en:"employer"},
    {cz:"zaměstnanec",pattern:"muž",en:"employee"},{cz:"zaměstnankyně",pattern:"růže",en:"employee (f)"},
    {cz:"ředitel",pattern:"muž",en:"director"},{cz:"ředitelka",pattern:"žena",en:"director (f)"},
    {cz:"vedoucí",pattern:"(adj)",en:"leader / head"},{cz:"pracovní doba",pattern:"žena",en:"working hours"},
    {cz:"směna",pattern:"žena",en:"shift (work)"},{cz:"mzda",pattern:"žena",en:"wage"},
    {cz:"plat",pattern:"hrad",en:"salary"},{cz:"odměna",pattern:"žena",en:"bonus"},
    {cz:"praxe",pattern:"růže",en:"experience"},{cz:"životopis",pattern:"hrad",en:"CV / resume"},
    {cz:"úřad práce",pattern:"hrad",en:"job centre"},{cz:"kancelář",pattern:"píseň",en:"office"},
    {cz:"svátek",pattern:"hrad",en:"public holiday"},{cz:"procházka",pattern:"žena",en:"walk"},
    {cz:"výlet",pattern:"hrad",en:"trip"},{cz:"hospoda",pattern:"žena",en:"pub"},
    {cz:"nakupování",pattern:"stavení",en:"shopping"},{cz:"návštěva",pattern:"žena",en:"visit"},
    {cz:"koníček",pattern:"hrad",en:"hobby"},{cz:"housle",pattern:"růže",en:"violin"},
    {cz:"šachy",pattern:"hrad",en:"chess"},{cz:"karty",pattern:"žena",en:"cards"},
    {cz:"kulečník",pattern:"hrad",en:"billiards"},{cz:"zahrada",pattern:"žena",en:"garden"},
    {cz:"nájem",pattern:"hrad",en:"rent"},{cz:"majitelka",pattern:"žena",en:"owner (f)"},
    {cz:"sousedka",pattern:"žena",en:"neighbour (f)"},{cz:"spolubydlící",pattern:"(adj)",en:"roommate"},
    {cz:"místnost",pattern:"kost",en:"room"},{cz:"kuchyně",pattern:"růže",en:"kitchen"},
    {cz:"záchod",pattern:"hrad",en:"toilet"},{cz:"dveře",pattern:"růže",en:"door"},
    {cz:"chodba",pattern:"žena",en:"corridor"},{cz:"schod",pattern:"hrad",en:"stair / step"},
    {cz:"garáž",pattern:"píseň",en:"garage"},{cz:"nábytek",pattern:"hrad",en:"furniture"},
    {cz:"stůl",pattern:"hrad",en:"table / desk"},{cz:"židle",pattern:"růže",en:"chair"},
    {cz:"skříň",pattern:"píseň",en:"wardrobe"},{cz:"gauč",pattern:"hrad",en:"couch"},
    {cz:"sprcha",pattern:"žena",en:"shower"},{cz:"vana",pattern:"žena",en:"bathtub"},
    {cz:"umyvadlo",pattern:"město",en:"washbasin"},{cz:"rádio",pattern:"město",en:"radio"},
    {cz:"lednička",pattern:"žena",en:"fridge"},{cz:"pračka",pattern:"žena",en:"washing machine"},
    {cz:"sporák",pattern:"hrad",en:"cooker"},{cz:"mikrovlnka",pattern:"žena",en:"microwave"},
    {cz:"lampa",pattern:"žena",en:"lamp"},{cz:"stěna",pattern:"žena",en:"wall"},
    {cz:"přestupek",pattern:"hrad",en:"offence"},{cz:"daň",pattern:"píseň",en:"tax"},
    {cz:"důchod",pattern:"hrad",en:"pension"},{cz:"mateřská",pattern:"(adj)",en:"maternity leave"},
    {cz:"OAMP",pattern:"hrad",en:"immigration dep."},{cz:"pobyt",pattern:"hrad",en:"residence"},
    {cz:"průkaz",pattern:"hrad",en:"ID card"},{cz:"formulář",pattern:"stroj",en:"form"},
    {cz:"změna",pattern:"žena",en:"change"},{cz:"žádost",pattern:"kost",en:"application"},
    {cz:"výpis",pattern:"hrad",en:"extract"},{cz:"soud",pattern:"hrad",en:"court"},
    {cz:"krádež",pattern:"píseň",en:"theft"},{cz:"pomoc",pattern:"kost",en:"help"},
    {cz:"hasič",pattern:"muž",en:"firefighter"},{cz:"záchranka",pattern:"žena",en:"ambulance"},
    {cz:"nehoda",pattern:"žena",en:"accident"},{cz:"porucha",pattern:"žena",en:"defect / failure"},
    {cz:"nebezpečí",pattern:"stavení",en:"danger"},{cz:"požár",pattern:"hrad",en:"fire"},
    {cz:"povodeň",pattern:"píseň",en:"flood"},{cz:"krize",pattern:"růže",en:"crisis"},
    {cz:"válka",pattern:"žena",en:"war"},{cz:"univerzita",pattern:"žena",en:"university"},
    {cz:"kurz",pattern:"hrad",en:"course"},{cz:"přihláška",pattern:"žena",en:"application"},
    {cz:"třída",pattern:"žena",en:"classroom"},{cz:"šatna",pattern:"žena",en:"cloakroom"},
    {cz:"tělocvična",pattern:"žena",en:"gym"},{cz:"jídelna",pattern:"žena",en:"dining room"},
    {cz:"knihovna",pattern:"žena",en:"library"},{cz:"papír",pattern:"hrad",en:"paper"},
    {cz:"sešit",pattern:"hrad",en:"exercise book"},{cz:"učebnice",pattern:"růže",en:"textbook"},
    {cz:"slovník",pattern:"hrad",en:"dictionary"},{cz:"notebook",pattern:"hrad",en:"laptop"},
    {cz:"propiska",pattern:"žena",en:"pen"},{cz:"školník",pattern:"pán",en:"janitor"},
    {cz:"uklízečka",pattern:"žena",en:"cleaning lady"},{cz:"žák",pattern:"pán",en:"pupil"},
    {cz:"žákyně",pattern:"růže",en:"pupil (f)"},{cz:"příklad",pattern:"hrad",en:"example"},
    {cz:"úkol",pattern:"hrad",en:"assignment"},{cz:"přestávka",pattern:"žena",en:"break / pause"},
    {cz:"hodina",pattern:"žena",en:"lesson"},{cz:"předmět",pattern:"hrad",en:"subject"},
    {cz:"čeština",pattern:"žena",en:"Czech language"},{cz:"angličtina",pattern:"žena",en:"English lang."},
    {cz:"matematika",pattern:"žena",en:"mathematics"},{cz:"fyzika",pattern:"žena",en:"physics"},
    {cz:"biologie",pattern:"růže",en:"biology"},{cz:"chemie",pattern:"růže",en:"chemistry"},
    {cz:"zeměpis",pattern:"hrad",en:"geography"},{cz:"dějepis",pattern:"hrad",en:"history"},
    {cz:"tělocvik",pattern:"hrad",en:"PE"},{cz:"obor",pattern:"hrad",en:"field (study)"},
    {cz:"právo",pattern:"město",en:"law"},{cz:"medicína",pattern:"žena",en:"medicine"},
    {cz:"informatika",pattern:"žena",en:"computer sci."},{cz:"ekonomie",pattern:"růže",en:"economics"},
    {cz:"test",pattern:"hrad",en:"test"},{cz:"zkouška",pattern:"žena",en:"exam"},
    {cz:"známka",pattern:"žena",en:"grade / mark"},{cz:"bod",pattern:"hrad",en:"point"},
    {cz:"chyba",pattern:"žena",en:"mistake / error"},{cz:"vzdělání",pattern:"stavení",en:"education"},
    {cz:"vysvědčení",pattern:"stavení",en:"school report"},{cz:"maturita",pattern:"žena",en:"leaving exam"},
    {cz:"diplom",pattern:"hrad",en:"university deg."},{cz:"hvězda",pattern:"žena",en:"star"},
    {cz:"měsíc",pattern:"stroj",en:"moon / month"},{cz:"hora",pattern:"žena",en:"mountain"},
    {cz:"nebe",pattern:"moře",en:"sky"},{cz:"řeka",pattern:"žena",en:"river"},
    {cz:"příroda",pattern:"žena",en:"nature"},{cz:"les",pattern:"hrad",en:"forest"},
    {cz:"pole",pattern:"moře",en:"field"},{cz:"rostlina",pattern:"žena",en:"plant"},
    {cz:"květina",pattern:"žena",en:"flower"},{cz:"růže",pattern:"růže",en:"rose"},
    {cz:"strom",pattern:"hrad",en:"tree"},{cz:"jezero",pattern:"město",en:"lake"},
    {cz:"zvíře",pattern:"kuře",en:"animal"},{cz:"pes",pattern:"pán",en:"dog"},
    {cz:"kočka",pattern:"žena",en:"cat"},{cz:"kůň",pattern:"muž",en:"horse"},
    {cz:"veterinář",pattern:"muž",en:"vet"},{cz:"počasí",pattern:"stavení",en:"weather"},
    {cz:"teplota",pattern:"žena",en:"temperature"},{cz:"slunce",pattern:"moře",en:"sun"},
    {cz:"mrak",pattern:"hrad",en:"cloud"},{cz:"vítr",pattern:"hrad",en:"wind"},
    {cz:"déšť",pattern:"stroj",en:"rain"},{cz:"sníh",pattern:"hrad",en:"snow"},
    {cz:"mráz",pattern:"hrad",en:"frost"},{cz:"bouřka",pattern:"žena",en:"storm"},
    {cz:"mlha",pattern:"žena",en:"fog"},{cz:"předpověď",pattern:"kost",en:"forecast"},
    {cz:"tělo",pattern:"město",en:"body"},{cz:"hlava",pattern:"žena",en:"head"},
    {cz:"nos",pattern:"hrad",en:"nose"},{cz:"pusa",pattern:"žena",en:"mouth"},
    {cz:"obličej",pattern:"stroj",en:"face"},{cz:"zub",pattern:"hrad",en:"tooth"},
    {cz:"jazyk",pattern:"hrad",en:"tongue / lang."},{cz:"krk",pattern:"hrad",en:"neck / throat"},
    {cz:"prst",pattern:"hrad",en:"finger / toe"},{cz:"záda",pattern:"město",en:"backs"},
    {cz:"srdce",pattern:"moře",en:"heart"},{cz:"břicho",pattern:"město",en:"belly"},
    {cz:"žaludek",pattern:"hrad",en:"stomach"},{cz:"kost",pattern:"kost",en:"bone"},
    {cz:"kůže",pattern:"růže",en:"skin"},{cz:"bolest",pattern:"kost",en:"pain"},
    {cz:"rýma",pattern:"žena",en:"runny nose"},{cz:"kašel",pattern:"stroj",en:"cough"},
    {cz:"průjem",pattern:"hrad",en:"diarrhea"},{cz:"zácpa",pattern:"žena",en:"constipation"},
    {cz:"horečka",pattern:"žena",en:"fever"},{cz:"tlak",pattern:"hrad",en:"pressure"},
    {cz:"rána",pattern:"žena",en:"wound"},{cz:"nemoc",pattern:"kost",en:"illness"},
    {cz:"operace",pattern:"růže",en:"surgery"},{cz:"úraz",pattern:"hrad",en:"injury"},
    {cz:"krev",pattern:"(irr)",en:"blood"},{cz:"vyšetření",pattern:"stavení",en:"examination"},
    {cz:"lék",pattern:"hrad",en:"medicine"},{cz:"alergie",pattern:"růže",en:"allergy"},
    {cz:"dieta",pattern:"žena",en:"diet"},{cz:"chřipka",pattern:"žena",en:"flu"},
    {cz:"ordinace",pattern:"růže",en:"the practice"},{cz:"čekárna",pattern:"žena",en:"waiting room"},
    {cz:"pohotovost",pattern:"kost",en:"emergency"},{cz:"očkování",pattern:"stavení",en:"vaccination"},
    {cz:"recept",pattern:"hrad",en:"prescription"},{cz:"pojištění",pattern:"stavení",en:"insurance"},
    {cz:"začátečník",pattern:"pán",en:"beginner"},{cz:"začátečnice",pattern:"růže",en:"beginner (f)"},
    {cz:"kamarádka",pattern:"žena",en:"friend (f)"},{cz:"známý",pattern:"mladý",en:"acquaintance"},
    {cz:"host",pattern:"kost",en:"guest"},{cz:"cizinec",pattern:"muž",en:"foreigner"},
    {cz:"cizinka",pattern:"žena",en:"foreigner (f)"},{cz:"společnost",pattern:"kost",en:"society / company"},
    {cz:"občan",pattern:"pán",en:"citizen"},{cz:"vláda",pattern:"žena",en:"government"},
    {cz:"ministerstvo",pattern:"město",en:"ministry"},{cz:"parlament",pattern:"hrad",en:"parliament"},
    {cz:"Senát",pattern:"hrad",en:"Senate"},{cz:"zákon",pattern:"hrad",en:"law / act"},
    {cz:"strana",pattern:"žena",en:"political party"},{cz:"volby",pattern:"žena",en:"elections"},
    {cz:"vesnice",pattern:"růže",en:"village"},{cz:"kraj",pattern:"stroj",en:"region (adm.)"},
    {cz:"nabíječka",pattern:"žena",en:"charger"},{cz:"heslo",pattern:"město",en:"password"},
    {cz:"příloha",pattern:"žena",en:"attachment"},{cz:"signál",pattern:"hrad",en:"signal"},
    {cz:"názor",pattern:"hrad",en:"opinion"},{cz:"rozdíl",pattern:"stroj",en:"difference"},
    {cz:"možnost",pattern:"kost",en:"opportunity"},{cz:"smlouva",pattern:"žena",en:"contract"},
    {cz:"razítko",pattern:"město",en:"stamp"},{cz:"vlk",pattern:"pán",en:"wolf"},
    {cz:"medvěd",pattern:"pán",en:"bear"},{cz:"pták",pattern:"pán",en:"bird"},
    {cz:"ryba",pattern:"žena",en:"fish"}
];